# SPDX-FileCopyrightText: The Pixel contributors
# SPDX-License-Identifier: MIT

[package]
name = "pixel-ultraflow"
version = "0.7.0"
edition.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
pixel-flow = { path = "../pixel-flow" }
serde = { workspace = true }
mutants = { workspace = true }
