//! Canonical capability-name registry, derived from `pixel_proto::Op` with
//! compile-time enforced parity.
//!
//! `crates/pixel/src/main.rs`'s `HookCmd::SessionStart` currently emits the
//! SessionStart hook's capability block from a hand-maintained `Vec<&str>`
//! literal, independent of `pixel_proto::Op`. That is exactly the
//! GitNexus-class bug this design is supposed to make structurally
//! impossible: if a new `Op` variant is added (or removed/renamed) and
//! nobody remembers to update that literal, the installed hook silently
//! drifts from what the binary actually implements — either claiming a
//! capability that doesn't exist, or failing to advertise one that does.
//!
//! This module is the fix: [`op_name`] matches every `Op` variant with no
//! wildcard arm, so adding a variant in `pixel-proto` without updating this
//! file is a **compile error** here, not a silent runtime drift. `ALL_OP_NAMES`
//! is generated by the same macro invocation that defines `op_name`, so the
//! list can never diverge from what the match actually accepts.
//!
//! `crates/pixel/src/main.rs` is outside this crate's exclusive ownership
//! for this change, so the hardcoded literal there has not been touched;
//! the necessary follow-up is to replace it with a call to
//! [`capability_block`].

use pixel_proto::Op;

macro_rules! op_registry {
    ($( $variant:pat => $name:literal ),+ $(,)?) => {
        /// Map a live `Op` instance to its canonical capability name.
        /// Exhaustive: adding an `Op` variant in pixel-proto without adding
        /// it here fails to compile.
        pub fn op_name(op: &Op) -> &'static str {
            match op {
                $( $variant => $name, )+
            }
        }

        /// Every capability name this registry knows about, in declaration
        /// order. Derived from the exact same list as [`op_name`], so it can
        /// never claim a name that isn't backed by a real `Op` variant.
        pub const ALL_OP_NAMES: &[&str] = &[ $( $name ),+ ];
    };
}

op_registry! {
    Op::Ping => "ping",
    Op::Recall { .. } => "recall",
    Op::Search { .. } => "search",
    Op::Targets { .. } => "targets",
    Op::Symbol { .. } => "symbol",
    Op::Context { .. } => "context",
    Op::Impact { .. } => "impact",
    Op::Uses { .. } => "uses",
    Op::Trace { .. } => "trace",
    Op::Processes { .. } => "processes",
    Op::Clusters { .. } => "clusters",
    Op::Changes { .. } => "changes",
    Op::Graph {} => "graph",
    Op::Status {} => "status",
    Op::Resolve { .. } => "resolve",
    Op::History { .. } => "history",
    Op::Lifecycle { .. } => "lifecycle",
    Op::Excavate { .. } => "excavate",
    Op::Reconcile { .. } => "reconcile",
    Op::Journal { .. } => "journal",
    Op::Inspect { .. } => "inspect",
    Op::Review { .. } => "review",
    Op::Diff { .. } => "diff",
    Op::HistoryOp { .. } => "history_op",
    Op::Publish { .. } => "publish",
    Op::Push { .. } => "push",
    Op::Ship { .. } => "ship",
    Op::BranchOp { .. } => "branch_op",
    Op::Update { .. } => "update",
    Op::Sync { .. } => "sync",
    Op::Shutdown => "shutdown",
}

/// Internal/control ops that aren't meaningful capabilities for an agent to
/// invoke directly: `recall` is served only by a recall-feature daemon
/// (a repo daemon answers it with "unsupported"), and `shutdown` is a
/// control op, not a retrieval/git capability.
pub const INTERNAL_OP_NAMES: &[&str] = &["recall", "shutdown"];

/// The capability names worth advertising to an agent session: every known
/// op minus the internal/control ones.
pub fn user_facing_op_names() -> Vec<&'static str> {
    ALL_OP_NAMES
        .iter()
        .copied()
        .filter(|n| !INTERNAL_OP_NAMES.contains(n))
        .collect()
}

/// Build the SessionStart hook's capability block JSON straight from the
/// live op registry — never a hand-maintained list that can drift from it.
pub fn capability_block(protocol_version: &str) -> serde_json::Value {
    serde_json::json!({
        "pixel": {
            "capabilities": user_facing_op_names(),
            "protocol_version": protocol_version,
        }
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn op_name_covers_every_declared_variant() {
        // Every entry in ALL_OP_NAMES came from the same macro invocation
        // that defines the exhaustive `op_name` match, so this is really
        // just asserting the list is non-empty and has no duplicates —
        // the real parity guarantee is enforced by the compiler at the
        // `op_registry!` call site above (no wildcard arm).
        let mut seen = std::collections::HashSet::new();
        for name in ALL_OP_NAMES {
            assert!(seen.insert(*name), "duplicate op name in registry: {name}");
        }
    }

    #[test]
    fn user_facing_excludes_internal_ops() {
        let user_facing = user_facing_op_names();
        for internal in INTERNAL_OP_NAMES {
            assert!(
                !user_facing.contains(internal),
                "{internal} should be excluded from user-facing capabilities"
            );
        }
        // Everything else in ALL_OP_NAMES should still be present.
        for name in ALL_OP_NAMES {
            if !INTERNAL_OP_NAMES.contains(name) {
                assert!(user_facing.contains(name), "{name} missing from user-facing list");
            }
        }
    }

    #[test]
    fn capability_block_shape() {
        let block = capability_block("v1");
        let caps = block["pixel"]["capabilities"]
            .as_array()
            .expect("capabilities array");
        assert!(!caps.is_empty());
        assert!(!caps.iter().any(|c| c == "recall" || c == "shutdown"));
        assert_eq!(block["pixel"]["protocol_version"], "v1");
    }

    #[test]
    fn op_name_matches_real_instances() {
        assert_eq!(op_name(&Op::Ping), "ping");
        assert_eq!(op_name(&Op::Shutdown), "shutdown");
        assert_eq!(
            op_name(&Op::Search {
                pattern: "x".into(),
                json: false,
                limit: None,
                offset: None,
                paths: None,
                scope: None,
            }),
            "search"
        );
    }
}
