#!/usr/bin/env python3
# SPDX-FileCopyrightText: The Pixel contributors
# SPDX-License-Identifier: MIT

"""Writes website/data/problem_trace.toml, the home's Problem chapter trace,
from a recording archived in docs/bench/problem-trace/.

The recording is `docs/motion/scripts/record-demo.sh` run with its default
task, then `docs/motion/scripts/trace.ts` on a copy of the script so that
`runs.json` lands beside the recording instead of over `docs/motion/src/demo`
(see docs/bench/problem-trace.md). Only the `vanilla` arm reaches the page.

The run shown is the one whose call count is the arm's median; among runs
tied on that count, the one whose lines of output are closest to the arm's
median lines. Each call is classified by its first command: `search` for the
Grep tool or a shell `grep`/`rg`, `read` for the Read tool or a shell
`sed`/`cat`/`head` (Opus prints file slices with `sed -n`), `other` for the
rest. Paths are shortened to their basename and a chained shell command to
its first command followed by an ellipsis.

Usage: scripts/problem-trace.py [docs/bench/problem-trace] > website/data/problem_trace.toml
"""

import json
import os
import re
import statistics
import sys


def kind(step):
    if step["tool"] == "Grep":
        return "search"
    if step["tool"] == "Read":
        return "read"
    cmd = re.sub(r"^\$ (cd [^;&]+[;&]+\s*)?", "", step["label"])
    if cmd.startswith(("grep", "rg")):
        return "search"
    if cmd.startswith(("sed", "cat", "head")):
        return "read"
    return "other"


def short(step):
    label = step["label"]
    if label.startswith("$ "):
        parts = [p for p in re.split(r"\s*(?:;|&&)\s*", label[2:]) if not p.startswith(("cd ", "echo"))]
        label = "$ " + parts[0] + (" …" if len(parts) > 1 else "")
    label = re.sub(r"(?:crates/)?[\w\-]+(?:/[\w\-\.\*]+)+\.\w+", lambda m: os.path.basename(m.group(0)), label)
    return re.sub(r" \| head(?: -\d+)?", "", label)


def toml_str(s):
    return json.dumps(s, ensure_ascii=False)


def main():
    root = sys.argv[1] if len(sys.argv) > 1 else "docs/bench/problem-trace"
    runs = json.load(open(os.path.join(root, "runs.json")))["vanilla"]
    meta = dict(line.split("=", 1) for line in open(os.path.join(root, "meta.txt")).read().splitlines() if "=" in line)
    calls = sorted(len(r["steps"]) for r in runs)
    med_calls = statistics.median(calls)
    med_lines = statistics.median(sum(s["lines"] for s in r["steps"]) for r in runs)
    tied = [r for r in runs if len(r["steps"]) == med_calls]
    shown = min(tied, key=lambda r: abs(sum(s["lines"] for s in r["steps"]) - med_lines))
    started = re.search(r"started=(\S+)", meta["arms"]).group(1)
    print(f"""# The Problem chapter's trace: every tool call one agent without Pixel made
# before answering the scoping task, from the recording archived in
# docs/bench/problem-trace/ (method and both arms' results in
# docs/bench/problem-trace.md). Generated by scripts/problem-trace.py; do not
# edit by hand. `calls` holds each vanilla run's call count, so the page
# computes the median it quotes; `head` and `tail` are how many calls stay
# visible around the folded middle.
recorded = {toml_str(started[:10])}
model = {toml_str(meta["model"].split()[0])}
effort = {toml_str(meta["model"].split("effort=")[1])}
claude = {toml_str(meta["claude"].split()[0])}
ref = {toml_str(meta["ref"].split()[0])}
prompt = {toml_str(meta["task"])}
run = {toml_str(shown["run"])}
calls = [{", ".join(str(c) for c in calls)}]
head = 6
tail = 2
""")
    for step in shown["steps"]:
        print(f"[[call]]\ncommand = {toml_str(short(step))}\nkind = {toml_str(kind(step))}\nlines = {step['lines']}\n")


if __name__ == "__main__":
    main()
