#!/usr/bin/env python3
# SPDX-FileCopyrightText: The Pixel contributors
# SPDX-License-Identifier: MIT

"""Writes website/data/scope.toml, the home's Scoping board, from the
recording the Problem chapter shows (docs/bench/problem-trace/).

The board is the task packet the Pixel arm received before its first call:
`packet.txt`, which scripts/scope-packet.sh reproduces with the recorded
binary. Its P0 targets are the files to start with, its P1 targets the
likely ones, and `base_files` the index size the grid draws. Each file's
`at` is its position in the recorded tree (REF's files without docs/motion,
which record-demo.sh drops), sorted, which is how the grid lays squares out.

`missed` lists what the packet did not name and every Pixel run's answer
did, by basename: the board's footnote says the packet is a starting point,
and these are the files that show it.

Usage: scripts/scope-board.py [docs/bench/problem-trace] > website/data/scope.toml
"""

import json
import os
import re
import subprocess
import sys


def toml_str(s):
    return json.dumps(s, ensure_ascii=False)


def main():
    root = sys.argv[1] if len(sys.argv) > 1 else "docs/bench/problem-trace"
    packet = open(os.path.join(root, "packet.txt")).read()
    meta = dict(line.split("=", 1) for line in open(os.path.join(root, "meta.txt")).read().splitlines() if "=" in line)
    ref = meta["ref"].split()[0]
    files = int(re.search(r"base_files=(\d+)", packet).group(1))
    targets = [json.loads(line) for line in packet.splitlines() if line.startswith('{"')]
    p0 = [t["path"] for t in targets if t["tier"] == "P0"]
    p1 = [t["path"] for t in targets if t["tier"] == "P1"]
    tree = subprocess.run(["git", "ls-tree", "-r", "--name-only", ref], check=True, capture_output=True, text=True).stdout
    tracked = sorted(p for p in tree.splitlines() if not p.startswith("docs/motion/"))
    at = {p: i for i, p in enumerate(tracked)}

    runs = json.load(open(os.path.join(root, "runs.json")))["pixel"]
    named = [set(re.findall(r"[\w\-]+\.\w+", r["answer"])) for r in runs]
    listed = {os.path.basename(p) for p in p0 + p1}
    every = set.intersection(*named)
    # Kept to source files the tree holds, so a word like `e.g` cannot pass.
    basenames = {os.path.basename(p) for p in tracked}
    missed = sorted(f for f in every - listed if f in basenames)

    print(f"""# The Scoping board: the task packet the Pixel arm of the Problem chapter's
# recording received before its first call (docs/bench/problem-trace.md,
# "The Scoping board"). Generated by scripts/scope-board.py from
# docs/bench/problem-trace/packet.txt; do not edit by hand. `files` is the
# index size the grid draws; each `at` is the file's position in the
# recorded tree, sorted. `missed` holds the files every one of the `runs`
# Pixel runs named in its answer that the packet left out.
ref = {toml_str(ref)}
recorded = {toml_str(re.search(r"started=(\S+)", meta["arms"]).group(1)[:10])}
task = {toml_str(re.match(r"Task: (.*?)\. ", meta["task"]).group(1))}
files = {files}
runs = {len(runs)}
missed = [{", ".join(toml_str(m) for m in missed)}]
p1 = [{", ".join(str(at[p]) for p in p1)}]""")
    for p in p0:
        print(f"""
[[p0]]
path = {toml_str(p)}
at = {at[p]}""")


if __name__ == "__main__":
    main()
