//! What act 1 scrolls through: real grep output and real file lines of this
//! repository, captured once, so the agent the intro shows searches the
//! way the recorded vanilla-6 run did (`docs/motion/src/demo/runs.json`).
//! The text is scenery: nothing reads it back, and it does not need to
//! follow the tree it was taken from.

pub(super) const GREP_LEASE: &[&str] = &[
    "crates/pixel-index/src/lock.rs:5://! `root/.pixel/build.lock`, builds the shard, and releases. Concurrent",
    "crates/pixel-recall/src/sources/claude.rs:426:            \"message\": {\"content\": [{\"type\": \"text\", \"text\": \"pl",
    "crates/pixel/tests/cli/release_check_cli.rs:105:    let out = pixel(&dir, &[\"check-release\", \"0.2.3\"]);",
    "crates/pixel/tests/cli/task_watchdog.rs:159:        holder_released.store(true, Ordering::SeqCst);",
    "crates/pixel/tests/cli/update_notice_cli.rs:1://! The release notice reaches a person at a terminal and nobody",
    "crates/pixel/src/main_tests/upgrade_target_tests.rs:15:        cargo_profile_dir(\"cargo build --profile dev-re",
    "crates/pixel/src/classify_setup.rs:312:    /// `/etc/os-release` when the platform ships one.",
    "crates/pixel/src/classify_setup.rs:1154:                os_release: None,",
    "crates/pixel/src/classify_setup.rs:1303:        assert_eq!(os_release_field(release, \"PRETTY_NAME\"), \"Ubuntu 2",
    "crates/pixel/src/task_hook.rs:908:                let (release, wait) = std::sync::mpsc::channel();",
    "crates/pixel/src/update_notice.rs:93:/// The tag in the URL `releases/latest` redirected to, or `None` when it",
    "crates/pixel/src/main.rs:938:        force_with_lease: bool,",
    "crates/pixel/src/main.rs:3868:fn release_upgrade_hint() -> Option<String> {",
    "crates/pixel/src/main.rs:4028:        \"bench\" => \"release\".into(),",
    "crates/pixel/src/main.rs:9012:    /// A `pixel-dev` built from a branch differs from the release's deployed",
    "crates/pixel/src/overview_intent.rs:24:    \"please\",",
    "crates/pixel-daemon/tests/all/watcher_freshness.rs:208:    release_tx.send(()).unwrap();",
    "crates/pixel-graph/src/resolve.rs:47://! candidate carries the source name (`use a::push as leased;` →",
    "crates/pixel-graph/src/build.rs:2636:    /// also what a passed-as-value reference writes (`run(leased)`), and",
    "crates/pixel-graph/src/extract.rs:3687:            [ImportBinding::aliased(\"push\", \"leased\")]",
    "crates/pixel-task/tests/all/core.rs:788:        pixel_task::runner::check_recovery(&lease),",
    "crates/pixel-task/src/runner.rs:431:        let path = root.path().join(\"lease.json\");",
    "crates/pixel-task/src/store.rs:626:            runner::verify_with_lease(source, &task.contract, &checks, &run",
    "crates/pixel-release/src/lib.rs:258:/// notes left under Unreleased would be silently dropped from it.",
    "crates/pixel-release/src/lib.rs:511:        let left_over = \"## [Unreleased]\\n\\n### Fixed\\n- not moved\\n- nor ",
    "crates/pixel-install/tests/install_tests.rs:90:/// line (its CHANGELOG entry is 2.1.261; earlier releases exit",
    "crates/pixel-install/src/config.rs:33:/// is pixel's, whichever of the two binaries reads it: a release instal",
    "crates/pixel-install/src/routing.rs:1799:            assert!(is_pixel_hook(legacy, release()), \"{legacy}\");",
    "crates/pixel-install/src/routing.rs:1952:        let (left, changed) = remove_pre_tool_use_guard(&delegated, r",
    "crates/pixel-install/src/routing.rs:2681:            has_delegate(value[\"hooks\"].as_object().unwrap(), release",
    "crates/pixel-install/src/pi_project.rs:12://! Releases up to 0.4.0 wrote the guard and a rules block under",
    "crates/pixel-ops/tests/all/rewrite_matrix.rs:468:        \"lease must have protected the remote\"",
    "crates/pixel-ops/src/publish.rs:246:        lock.release();",
    "crates/pixel-ops/src/reconcile.rs:398:    // `origin/<branch>` oid instead succeeds). This is what makes the l",
    "crates/pixel-ops/src/reconcile.rs:916:        lock.release();",
    "crates/pixel-ops/src/reconcile.rs:1242:/// Leased push with `--force-with-lease=<branch>:<lease_oid>`, where",
    "crates/pixel-ops/src/branch.rs:65:        lock.release();",
    "crates/pixel-ops/src/push.rs:171:        lock.release();",
    "crates/pixel-ops/src/push.rs:493:    fn force_with_lease_pushes_rewritten_history_without_tracking_ref() {",
    "crates/pixel-ops/src/lock.rs:171:        lock2.release();",
];

pub(super) const GREP_FORCE: &[&str] = &[
    "crates/pixel-proto/src/op.rs:264:        force_with_lease: Option<bool>,",
    "crates/pixel/src/guard.rs:4674:        // Plain pushes — INCLUDING `--force-with-lease`, which the",
    "crates/pixel/src/guard.rs:5909:    fn substitute_push_plain_and_with_lease() {",
    "crates/pixel/src/guard.rs:5925:            \"git push --force-with-lease origin main\",",
    "crates/pixel/src/main.rs:975:        force_with_lease: bool,",
    "crates/pixel/src/main.rs:6018:                force_with_lease,",
    "crates/pixel-daemon/src/api.rs:1076:                    force_with_lease: force_with_lease.unwrap_or(false),",
    "crates/pixel-graph/src/build.rs:96:///    (`use a::push as leased;`, `import { push as leased }`), so T1 links",
    "crates/pixel-graph/src/build.rs:2653:            \"import { push as leased, LIMIT, helper as aid } from \\\"./pus",
    "crates/pixel-graph/src/extract.rs:3563:            \"use crate::push::{PushOptions, push as leased};\",",
    "crates/pixel-graph/src/extract.rs:3707:        let source = b\"import { push as leased, publish } from \\\"./push",
    "crates/pixel-graph/src/store.rs:2305:        assert_eq!(decode_bindings(\" push, leased=push,,\"), bindings);",
    "crates/pixel-ops/src/reconcile.rs:170:    /// commit. With `push: \"auto\"`, both the feature branch (leased) an",
    "crates/pixel-ops/src/reconcile.rs:1168:            let lease_arg = format!(\"--force-with-lease={branch}:{upstr",
    "crates/pixel-ops/src/reconcile.rs:1259:    match runner.run(&[\"push\", &lease_arg, \"origin\", branch]) {",
    "crates/pixel-ops/src/push.rs:104:/// EXPLICIT `--force-with-lease=<dst>:<oid>` form. Bare `--force-with-lease`",
    "crates/pixel-ops/src/push.rs:426:            force_with_lease: false,",
    "crates/pixel-ops/src/push.rs:503:            force_with_lease: false,",
    "crates/pixel-ops/src/ship.rs:32:    force_with_lease: bool,",
    "crates/pixel-ops/src/rewrite.rs:59:    /// Push the rewritten branch with `--force-with-lease` after squashing",
];

pub(super) const PUSH_RS: &[&str] = &[
    "//! `push` — leased push with crash-safe journaling.",
    "//!",
    "//! Phases: started → push_started → terminal",
    "//! Crash at push_started → NETWORK_AMBIGUITY (push may have succeeded).",
    "//! Crash at remote:returned → success (push already happened).",
    "",
    "use std::path::Path;",
    "",
    "use serde_json::{Value, json};",
    "",
    "use pixel_git::GitRunner;",
    "",
    "use crate::durable::{sha256_hex, state_root};",
    "use crate::journal::{BeginOutcome, JournalOperation, JournalPhase, OperationJournal};",
    "use crate::lock::RepositoryLock;",
    "use crate::repo::repo_identity;",
    "",
    "#[derive(Debug, Clone)]",
    "pub struct PushOptions {",
    "    pub remote: String,",
    "    pub refspec: String,",
    "    pub request_id: String,",
    "    pub force_with_lease: bool,",
    "}",
    "",
    "pub type PushProbe = Box<dyn FnMut(&str) -> Result<(), String>>;",
    "",
    "/// Split a refspec into its (source, destination) halves.",
    "///",
    "/// `main` → (`main`, `main`); `src:dst` → (`src`, `dst`). A leading `+`",
    "/// (git's own force marker) is stripped from the source side — pixel expresses",
    "/// force through `force_with_lease`, never through refspec syntax.",
    "fn split_refspec(refspec: &str) -> (String, String) {",
    "    match refspec.split_once(':') {",
    "        Some((src, dst)) => (",
    "            src.trim_start_matches('+').to_string(),",
    "            dst.trim_start_matches('+').to_string(),",
    "        ),",
    "        None => {",
    "            let one = refspec.trim_start_matches('+').to_string();",
    "            (one.clone(), one)",
    "        }",
    "    }",
    "}",
    "",
    "/// Validate both halves of a refspec independently.",
    "///",
    "/// `validate_ref` rejects `:` because a colon is not legal *inside* a ref name.",
];

pub(super) const GREP_SHIP: &[&str] = &[
    "crates/pixel-ops/src/ship.rs:20:    ship_with_lease(root, message, files, remote, refspec, request_id, false)",
    "crates/pixel-ops/src/reconcile.rs:169:    /// to the rebased feature head — ff-only, never force, never a merg",
    "crates/pixel-ops/src/reconcile.rs:393:    // of) the remote whenever a lease is about to be used, so leasing",
    "crates/pixel-ops/src/reconcile.rs:488:                match attempt_lease_push_or_reclassify(&runner, &branch,",
    "crates/pixel-ops/src/reconcile.rs:776:                                    match attempt_lease_push_or_reclassi",
    "crates/pixel-ops/src/reconcile.rs:937:        lock.release();",
    "crates/pixel-ops/src/reconcile.rs:992:             {remote_target} ({remote_target_oid}); refusing to move it ",
    "crates/pixel-ops/src/reconcile.rs:1165:    // of the remote target by construction; no force of any kind).",
    "crates/pixel-ops/src/reconcile.rs:1252:fn attempt_lease_push_or_reclassify(",
    "crates/pixel/src/guard.rs:22://!    `git push --force`. The original command is still allowed to proceed.",
    "crates/pixel/src/guard.rs:691:fn enforce_reason(provider: Provider, payload: &Value) -> Option<String> {",
    "crates/pixel/src/guard.rs:1025:fn enforce_shell_for_provider(",
    "crates/pixel/src/guard.rs:1120:        \"cat\" | \"head\" | \"tail\" => repo_read_reason(args, 0, cwd, root, enforce",
    "crates/pixel/src/guard.rs:1212:    let reason = enforce_reason(provider, payload)?;",
    "crates/pixel/src/guard.rs:3314:/// Read the enforcement manifest, accepting BOTH shapes:",
    "crates/pixel/src/guard.rs:4306:                \"BLOCKED by pixel-targets-guard: `git branch -D` force-deletes ",
    "crates/pixel/src/guard.rs:4450:/// | `git checkout -B` / plain `git checkout <ref>`  | force-reset / plain swi",
    "crates/pixel/src/guard.rs:5463:            \"git push --force-with-lease=main origin main\",",
    "crates/pixel/src/guard.rs:5925:            \"git push --force-with-lease origin main\",",
    "crates/pixel/src/guard.rs:6427:    /// the only decision that yields to enforced Pixel policy. Denials, other",
    "crates/pixel/src/guard.rs:7872:            enforce_leaf(segment, &words, false, &root, &root, true),",
    "crates/pixel/src/guard.rs:8011:    /// The camelCase alias is applied where [`enforce_reason`] decides the",
    "crates/pixel/src/guard.rs:8045:        let leaf = |command: &str, enforce: bool| {",
    "crates/pixel/src/guard.rs:8151:    fn enforce_leaf_explains_the_rtk_read_line_range_mistake() {",
];

pub(super) const RECONCILE_RS: &[&str] = &[
    "    }",
    "}",
    "",
    "enum LeaseOutcome {",
    "    Pushed,",
    "    Raced {",
    "        error: String,",
    "        ahead: u64,",
    "        behind: u64,",
    "    },",
    "}",
    "",
    "/// Leased push with `--force-with-lease=<branch>:<lease_oid>`, where",
    "/// `lease_oid` is the OID *this call's own fetch* just observed — the",
    "/// one-call design makes the lease airtight (no separately-transcribed OID",
    "/// that could go stale between a caller's read and its push).",
    "///",
    "/// On any push failure (most commonly the remote having moved since our",
    "/// fetch, i.e. a lease rejection), this performs exactly ONE re-fetch of the",
    "/// branch plus one reclassification and returns that as data — it never",
    "/// retries the push itself. A second blind retry is exactly the failure mode",
    "/// this function exists to rule out.",
    "fn attempt_lease_push_or_reclassify(",
    "    runner: &GitRunner,",
    "    branch: &str,",
    "    lease_oid: &str,",
    "    upstream: &str,",
    ") -> LeaseOutcome {",
    "    let lease_arg = format!(\"--force-with-lease={branch}:{lease_oid}\");",
    "    match runner.run(&[\"push\", &lease_arg, \"origin\", branch]) {",
    "        Ok(_) => LeaseOutcome::Pushed,",
    "        Err(e) => {",
    "            let _ = runner.run(&[\"fetch\", \"--end-of-options\", \"origin\", branch]);",
];

pub(super) const GREP_JOURNAL: &[&str] = &[
    "46:pub enum JournalPhase {",
    "55:impl std::fmt::Display for JournalPhase {",
    "59:            JournalPhase::IndexStaged => write!(f, \"index_staged\"),",
    "60:            JournalPhase::CommitObserved => write!(f, \"commit_observed\"),",
    "62:            JournalPhase::RefUpdateStarted => write!(f, \"ref_update_started\"),",
    "75:    pub phase: JournalPhase,",
    "90:        phase: JournalPhase,",
    "221:            JournalPhase::Terminal => {",
    "260:        self.transition(request_id, repo_key, JournalPhase::Terminal, Some(result))?;",
    "306:            if record.phase != JournalPhase::Terminal {",
    "378:        j.transition(\"req-2\", \"repo-key\", JournalPhase::IndexStaged, None)",
    "409:                assert_eq!(phase, JournalPhase::PushStarted);",
    "524:        j.transition(\"req-race\", \"repo-key\", JournalPhase::IndexStaged, None)",
    "554:        j.transition(\"req-5\", \"repo-key\", JournalPhase::IndexStaged, None)",
];

pub(super) const GREP_PUSH: &[&str] = &[
    "crates/pixel-proto/src/op.rs:191:        push: Option<String>,",
    "crates/pixel-proto/src/op.rs:259:    /// Leased push with crash-safe journaling.",
    "crates/pixel-proto/src/op.rs:472:    \"push\",",
    "crates/pixel-proto/src/op.rs:669:        assert_eq!(value[\"push\"], true);",
    "crates/pixel-proto/src/op.rs:874:                \"push\",",
    "crates/pixel-daemon/src/api.rs:822:            by_file.entry(m.path.clone()).or_default().push_str(&m.line);",
    "crates/pixel-daemon/src/api.rs:1022:            Request::Reconcile { strategy, push, into, request_id } => {",
    "crates/pixel-daemon/src/api.rs:1060:                    push: push.unwrap_or(false),",
    "crates/pixel-daemon/src/api.rs:1302:            arr.push(entry);",
    "crates/pixel-daemon/src/api.rs:1338:            cap_hits.push((",
    "crates/pixel-daemon/src/api.rs:1528:                    probe_caps.push(format!(",
    "crates/pixel-daemon/src/api.rs:1596:                    graph_neighbors.push((path, reason));",
    "crates/pixel-daemon/src/api.rs:1988:                reserved.push(key);",
    "crates/pixel-daemon/src/api.rs:2890:                    keys.push(n);",
    "crates/pixel-daemon/src/api.rs:3162:            grouped.push((f, syms));",
    "crates/pixel-daemon/src/api.rs:3478:            out.push('\\\\');",
    "crates/pixel-daemon/src/api.rs:3533:                caps.push(\"results truncated by an output cap\".to_string()",
    "crates/pixel-daemon/src/api.rs:3558:        caps.push(",
    "crates/pixel-daemon/src/api.rs:3577:        basis.push_str(&caps.join(\"; \"));",
    "crates/pixel-daemon/src/api.rs:3844:        caps.push(format!(",
    "crates/pixel-daemon/src/api.rs:4137:            snippet.push('\\n');",
    "crates/pixel-daemon/src/api.rs:4659:        by_file.entry(m.path.clone()).or_default().push(m.clone());",
    "crates/pixel-daemon/src/api.rs:5152:                \"STALE_REMOTE: leased push rejected — the remote no longer",
    "crates/pixel-daemon/src/api.rs:6474:                seen.push(m[\"path\"].as_str().unwrap().to_string());",
];

pub(super) const GREP_CRASH: &[&str] = &[
    "1://! Crash matrix tests for `publish` and `push`.",
    "21://!     file survives, and a crash at `journal:push_started` surfaces",
    "44:use pixel_ops::push::{PushOptions, PushProbe, push_with_state};",
    "290:                    out.push(path);",
    "504:/// Faithful port of usable-git's `pushFixture()`: local + bare remote, an",
    "507:fn init_push_fixture(root: &Path, remote: &Path) {",
    "531:/// Phases at which the push probe fires (in execution order):",
    "537:fn push_crash_at_phase(phase: &str) {",
    "553:    git(root, &[\"push\", \"-q\", \"origin\", \"unrelated\"]);",
    "566:    // Untracked local file that must survive the push attempt untouched.",
    "577:    //    `push_with_state` call.",
    "590:    let retry = push_with_state(root, &opts, None, &state_root);",
    "609:            \"phase {phase}: remote main changed despite NETWORK_AMBIGUITY (push should not have run)\",",
    "616:            \"phase {phase}: retry did not report pushed=true\",",
    "624:            \"phase {phase}: remote main ({remote_main}) != source_oid ({source_oid}) after push\",",
    "652:    push_crash_at_phase(\"journal:started\");",
    "657:    push_crash_at_phase(\"journal:push_started\");",
    "662:    push_crash_at_phase(\"remote:returned\");",
];

pub(super) const GREP_RUN: &[&str] = &[
    "crates/pixel-git/src/runner.rs:77:    /// stderr, trimmed and redacted like the text of a `NonZeroExit`.",
    "crates/pixel-git/src/runner.rs:131:    /// stderr on failure is redacted before being embedded in `GitError`.",
    "crates/pixel-git/src/runner.rs:244:                stderr: check.stderr,",
    "crates/pixel-git/src/runner.rs:386:/// stdout and stderr under the byte cap, poll for the timeout, and return",
    "crates/pixel-git/src/runner.rs:409:    cmd.stderr(Stdio::piped());",
    "crates/pixel-git/src/runner.rs:432:    let stderr_thread =",
    "crates/pixel-git/src/runner.rs:516:        .map_err(|_| GitError::Io(std::io::Error::other(\"stderr reader thre",
    "crates/pixel-git/src/runner.rs:759:        assert_eq!(out.stderr, \"warned\");",
    "crates/pixel-git/src/runner.rs:872:        assert!(!out.stderr.is_empty(), \"{out:?}\");",
    "crates/pixel-git/src/runner.rs:946:            Err(GitError::NonZeroExit { code, stderr, .. }) => {",
    "crates/pixel-git/src/redact.rs:2://! (primarily stderr embedded in `GitError::NonZeroExit`) before it can ever",
    "crates/pixel-git/src/plumbing.rs:409:    /// stderr is captured and redacted instead of inheriting the caller'",
    "crates/pixel-git/src/batch.rs:248:    let stderr = child.stderr.take().expect(\"piped stderr\");",
    "crates/pixel-git/src/batch.rs:274:                // The reader and stderr threads are left to end on their",
    "crates/pixel-git/src/batch.rs:294:            stderr: redact(String::from_utf8_lossy(&stderr).trim()),",
    "crates/pixel-git/src/batch.rs:587:    fn an_early_exit_is_an_error_carrying_the_exit_code_and_stderr() {",
    "crates/pixel-git/src/error.rs:10:pub enum GitError {",
    "crates/pixel-git/src/error.rs:24:        stderr: String,",
];
