//! `reconcile` — Engine 4: one-call deterministic branch sync.
//!
//! Eliminates OID transcription: the snapshot inside the lock supplies all
//! expectations, making STALE_STATE structurally impossible within the op.
//!
//! Flow: snapshot → fetch (branch-scoped) → classify (rev-list --left-right
//! --count) → up_to_date | fast_forward | ahead (leased push) | diverged
//! (report or rebase-if-clean).
//!
//! Divergence policy: default "report"; "rebase-if-clean" is explicit opt-in.
//! Never merge commits. Zero-textual-conflict rebase is deterministic work.
//! Mechanics: clean worktree required → prove cleanliness per replayed
//! commit with `git merge-tree --write-tree` → non-interactive `git rebase`
//! under journal → backup ref first → any surprise conflict → `rebase --abort`
//! + diverged report.
//!
//! Lease race: if the remote moves between this call's own fetch and its
//! push attempt, exactly one re-fetch + reclassify is performed, then a
//! terminal report is returned — never a second blind retry.

use std::collections::BTreeMap;
use std::path::Path;

use serde_json::{Value, json};

use pixel_git::GitRunner;

use crate::durable::{sha256_hex, state_root};
use crate::journal::{BeginOutcome, JournalOperation, OperationJournal};
use crate::lock::RepositoryLock;
use crate::repo::repo_identity;

/// True if a rebase is currently in progress (`.git/rebase-merge/` or
/// `.git/rebase-apply/` exists). Guards `rebase --abort` calls so they
/// only fire when there is actually a rebase to abort — calling
/// `--abort` without an active rebase is a git error that can mask the
/// real failure in the surrounding error-handling path.
fn rebase_in_progress(root: &Path) -> bool {
    let git_dir = resolve_git_dir(root);
    git_dir.join("rebase-merge").is_dir() || git_dir.join("rebase-apply").is_dir()
}

/// `git rebase --continue` after every conflicted path was staged. Goes
/// through the runner so a hook or an editor that hangs hits the runner's
/// timeout instead of parking the daemon's request thread; `GIT_EDITOR=true`
/// keeps git from opening one for the commit message. True only on exit 0
/// (a rebase with nothing to continue exits 128).
fn continue_rebase(runner: &GitRunner) -> bool {
    runner
        .run_output(&["rebase", "--continue"], &[("GIT_EDITOR", "true")])
        .is_ok_and(|out| out.success())
}

/// Resolve the real git directory for `root`.
///
/// Worktree support: `.git` may be a file containing `gitdir: <path>`
/// rather than a directory.
fn resolve_git_dir(root: &Path) -> std::path::PathBuf {
    let git_dir = root.join(".git");
    if git_dir.is_file() {
        std::fs::read_to_string(&git_dir)
            .ok()
            .and_then(|s| {
                s.lines()
                    .find(|l| l.starts_with("gitdir:"))
                    .map(|l| l.trim_start_matches("gitdir:").trim().to_string())
            })
            .map(std::path::PathBuf::from)
            .unwrap_or(git_dir)
    } else {
        git_dir
    }
}

/// Name of the git operation already in progress in `root`, if any.
///
/// `reconcile` drives `git rebase` and aborts it on failure. If the user
/// is *already* mid-rebase, mid-merge, or mid-cherry-pick when reconcile
/// is invoked, that abort would destroy their in-progress work — and a
/// paused `rebase -i` leaves a clean `status --porcelain`, so the dirty
/// check does not catch it. Refuse up front instead.
fn integration_in_progress(root: &Path) -> Option<&'static str> {
    let git_dir = resolve_git_dir(root);
    if git_dir.join("rebase-merge").is_dir() || git_dir.join("rebase-apply").is_dir() {
        return Some("a rebase");
    }
    if git_dir.join("MERGE_HEAD").exists() {
        return Some("a merge");
    }
    if git_dir.join("CHERRY_PICK_HEAD").exists() {
        return Some("a cherry-pick");
    }
    if git_dir.join("REVERT_HEAD").exists() {
        return Some("a revert");
    }
    None
}

/// Abort the current rebase if one is in progress. No-op if the repo is
/// not mid-rebase — avoids a spurious git error that would mask the real
/// failure in the caller's error-handling path.
fn safe_rebase_abort(runner: &GitRunner) {
    if rebase_in_progress(runner.root()) {
        let _ = runner.run_opt(&["rebase", "--abort"]);
    }
}

/// True if `path` is inside a pixel sidecar directory — `.pixel/` (current)
/// or `.gitpixel/` (legacy; `pixel migrate` is opt-in, so pre-migration
/// repos still carry it).
///
/// These are pixel-generated artifacts (index, graph, action log) that are
/// normally untracked, never touched by a rebase (which only replays tracked
/// files), and regenerated by the pixel daemon. They must not gate a
/// rebase's clean-worktree precondition — otherwise the daemon's own
/// sidecar writes block every `reconcile --into` / `rebase-if-clean` call.
fn is_pixel_sidecar(path: &str) -> bool {
    path == ".pixel"
        || path.starts_with(".pixel/")
        || path == ".gitpixel"
        || path.starts_with(".gitpixel/")
}

/// Filter pixel-sidecar entries from a `status_porcelain_or_err` result,
/// returning only entries that represent genuine working-tree dirtiness.
///
/// Only UNTRACKED (`??`) sidecar entries are dropped. Sidecar files are
/// normally never tracked, but that is an assumption, not an invariant: a
/// repo that commits one (e.g. a checked-in `.pixel/targets.json`) has real,
/// rebase-clobberable dirtiness when it is modified — so tracked and
/// unmerged sidecar entries always count as dirty.
fn dirty_excluding_sidecar(
    runner: &GitRunner,
    refuse_msg: &str,
) -> Result<Vec<(String, String)>, String> {
    let dirty = runner
        .status_porcelain_or_err()
        .map_err(|e| format!("{refuse_msg}: {e}"))?;
    Ok(dirty
        .into_iter()
        .filter(|(xy, p)| !ignorable_sidecar_entry(xy, p))
        .collect())
}

/// True for a porcelain status entry the clean-worktree gates may ignore:
/// an UNTRACKED file inside a pixel sidecar directory.
fn ignorable_sidecar_entry(xy: &str, path: &str) -> bool {
    xy == "??" && is_pixel_sidecar(path)
}

/// Per-path hunk cap (bytes). Individual `ours`/`theirs` hunks are truncated
/// past this with `hunk_truncated: true`.
const HUNK_MAX_BYTES: usize = 32 * 1024;
/// Whole-report cap (bytes, approximate — measured over each conflict
/// entry's serialized size as it is accumulated). Past this, remaining
/// conflict entries are dropped and `report_truncated: true` is set.
const REPORT_MAX_BYTES: usize = 256 * 1024;

#[derive(Debug, Clone)]
pub struct ReconcileOptions {
    pub strategy: String, // "report" | "rebase-if-clean"
    pub push: String,     // "auto" | "none" ("never" accepted as an alias of "none")
    pub request_id: String,
    /// `--into <target>` integration mode. `None` (the default) preserves the
    /// existing behavior exactly. `Some(target)` means: fetch the remote
    /// target, rebase the CURRENT branch onto `origin/<target>` (same
    /// merge-tree proof path, backup ref, and structured-conflict refusal as
    /// `rebase-if-clean`), then fast-forward the LOCAL `<target>` branch ref
    /// to the rebased feature head — ff-only, never force, never a merge
    /// commit. With `push: "auto"`, both the feature branch (leased) and the
    /// target (plain ff push) are pushed. The `strategy` field is ignored in
    /// this mode: `--into` inherently requires the rebase proof path.
    pub into_target: Option<String>,
}

/// Validate and normalize the `--push` value. Accepted: `"auto"` (push when
/// safe), `"none"` (never push), and `"never"` as an explicit alias of
/// `"none"` (older rule text documented it). Anything else is a structured
/// error naming the accepted values — previously any unrecognized string
/// (a typo like `--push always`, or the once-documented `never`) silently
/// meant don't-push.
fn validate_push_mode(push: &str) -> Result<&'static str, String> {
    match push {
        "auto" => Ok("auto"),
        "none" | "never" => Ok("none"),
        other => Err(format!(
            "invalid push value {other:?}: accepted values are \"auto\" (push when safe) \
             or \"none\" (never push; \"never\" is an accepted alias of \"none\")"
        )),
    }
}

pub fn reconcile(root: &Path, opts: &ReconcileOptions) -> Result<Value, String> {
    reconcile_with_hooks(root, opts, None)
}

/// Write a `.pixel/reconcile-conflict.json` state file so the guard knows
/// `pixel sync-branch` has reported a conflict and should allow raw `git rebase`
/// as an escape hatch. Cleared on successful reconcile or by `pixel scope-task --clear`.
fn write_conflict_state(root: &Path, conflict_count: usize) {
    let pixel_dir = pixel_git::sidecar::dir(root);
    if pixel_git::sidecar::private_dir(&pixel_dir).is_err() {
        return;
    }
    let state = json!({
        "conflict_count": conflict_count,
        "written_unix": std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map_or(0, |d| d.as_secs()),
    });
    // Replaced by rename, never written through a link at the name.
    let _ = pixel_git::nofollow::write_replace(
        &pixel_dir.join("reconcile-conflict.json"),
        serde_json::to_string_pretty(&state)
            .unwrap_or_default()
            .as_bytes(),
        pixel_git::nofollow::PRIVATE_MODE,
    );
}

/// Remove the conflict state file — called on successful reconcile.
fn clear_conflict_state(root: &Path) {
    let _ = std::fs::remove_file(root.join(".pixel").join("reconcile-conflict.json"));
}

/// Resolve conflict markers in a worktree file by union-merging both sides.
///
/// During a rebase, git writes conflict markers (`<<<<<<<`, `=======`, `>>>>>>>`)
/// into the worktree file. This function reads the file, extracts both sides
/// of each conflict hunk, and unions them (both sides' content kept, in order:
/// ours then theirs). This is safe for additive conflicts where both sides
/// added different content to the same region.
///
/// Returns true if all conflict markers were resolved, false if the file
/// couldn't be read or had an unexpected conflict marker structure.
fn auto_resolve_conflict_markers(_runner: &GitRunner, root: &Path, path: &str) -> bool {
    let worktree_path = root.join(path);
    let Ok(content) = std::fs::read_to_string(&worktree_path) else {
        return false;
    };

    // If no conflict markers, file is already resolved.
    if !content.contains("<<<<<<<") {
        return true;
    }

    let mut resolved_lines: Vec<String> = Vec::new();
    let lines = content.lines().peekable();
    let mut in_ours = false;
    let mut in_theirs = false;
    let mut ours_lines: Vec<String> = Vec::new();
    let mut theirs_lines: Vec<String> = Vec::new();

    for line in lines {
        if line.starts_with("<<<<<<<") {
            in_ours = true;
            ours_lines.clear();
            theirs_lines.clear();
        } else if line.starts_with("=======") && in_ours {
            in_ours = false;
            in_theirs = true;
        } else if line.starts_with(">>>>>>>") && in_theirs {
            in_theirs = false;
            // Union: ours first, then theirs.
            resolved_lines.append(&mut ours_lines);
            resolved_lines.append(&mut theirs_lines);
        } else if in_ours {
            ours_lines.push(line.to_string());
        } else if in_theirs {
            theirs_lines.push(line.to_string());
        } else {
            resolved_lines.push(line.to_string());
        }
    }

    // If we still have unresolved markers, the structure was unexpected.
    if in_ours || in_theirs {
        return false;
    }

    let resolved_content = resolved_lines.join("\n") + "\n";
    std::fs::write(&worktree_path, resolved_content).is_ok()
}

/// Test seam mirroring `push::PushProbe`: `pre_push_hook`, when given, runs
/// exactly once, right after this call's own fetch (`upstream_oid` has just
/// been captured) and before any leased push is attempted — the precise
/// window a "remote moved after our fetch, before our push" race occupies.
/// Production callers always go through `reconcile()`, which passes `None`;
/// this exists so the lease-race path (single re-fetch + reclassify, never a
/// second blind retry) can be exercised deterministically in tests instead
/// of relying on incidental timing.
pub fn reconcile_with_hooks(
    root: &Path,
    opts: &ReconcileOptions,
    mut pre_push_hook: Option<Box<dyn FnMut()>>,
) -> Result<Value, String> {
    // Refuse BEFORE touching any state: reconcile drives `git rebase` and
    // aborts it on failure, which would destroy an operation the user
    // started themselves. A paused `rebase -i` has a clean working tree,
    // so the dirty check below does not cover this.
    if let Some(op) = integration_in_progress(root) {
        return Err(format!(
            "{op} is already in progress in this repository; \
             pixel sync-branch would abort it. Finish it (git rebase --continue, \
             git merge --continue, git cherry-pick --continue) or abort it \
             yourself, then re-run pixel sync-branch."
        ));
    }

    // Clear any stale conflict state from a previous reconcile attempt.
    // If this call finds a new conflict, it will write a fresh state file.
    clear_conflict_state(root);

    // Validate BEFORE any journal/lock/git work — a bad value must be a
    // structured error, never a silent don't-push. The normalized mode is
    // also what gets hashed, so "never" and "none" replay identically.
    let push_mode = validate_push_mode(&opts.push)?;

    let runner = GitRunner::new(root);
    let repo_key = repo_identity(root);
    // `into_target` participates in the replay-identity hash: the same
    // request_id with a different integration target must never replay a
    // cached result computed for another target (or for plain sync mode).
    let input_hash = sha256_hex(&format!(
        "{}\u{0}{}\u{0}{}",
        opts.strategy,
        push_mode,
        opts.into_target.as_deref().unwrap_or("")
    ));

    let state_root = state_root();
    let journal = OperationJournal::with_state_root(state_root.clone());

    // The wire surface (pixel-proto's `Request::Reconcile` / pixel-daemon's
    // `op_reconcile`) does not currently thread a client-supplied
    // `request_id` through — every real dispatch arrives here with
    // `opts.request_id == ""`, which `journal.begin` rejects outright
    // ("requestId must be 1-128 chars"), hard-failing every call. Default to
    // a fresh UUID so the op is at least callable end-to-end; the tradeoff is
    // that crash-resume replay (`BeginOutcome::Replay`/`Resume`) is only
    // reachable for callers who supply their own stable `request_id`
    // explicitly — see the final report for the upstream wiring gap this
    // papers over.
    let request_id = if opts.request_id.is_empty() {
        uuid::Uuid::new_v4().to_string()
    } else {
        opts.request_id.clone()
    };

    let outcome = journal.begin(
        &request_id,
        JournalOperation::Update,
        &repo_key,
        &input_hash,
    )?;
    if let BeginOutcome::Replay(result) = outcome {
        return Ok(result);
    }

    let mut lock = RepositoryLock::acquire_with_state_root(&repo_key, &state_root)
        .map_err(|_| "repository is busy".to_string())?;

    // Snapshot current state.
    let head = runner.rev_parse_head().ok_or("no HEAD")?;
    let branch = runner
        .current_branch()
        .unwrap_or_else(|| "HEAD".to_string());

    // `--into <target>` integration mode: an entirely separate flow that
    // rebases the CURRENT branch onto origin/<target> and fast-forwards the
    // local <target> ref to the rebased head. Dispatched before the plain
    // sync classification below, which remains byte-for-byte unchanged for
    // `into_target: None` callers.
    if let Some(target) = opts.into_target.as_deref() {
        let result = reconcile_into(root, &runner, &mut lock, &head, &branch, target, push_mode)?;
        journal.complete(&request_id, &repo_key, result.clone())?;
        lock.release();
        return Ok(result);
    }

    let upstream = format!("origin/{branch}");

    // Branch-scoped fetch (idempotent, outside journal transitions). Fetches
    // only this branch rather than every ref on the remote — still updates
    // `refs/remotes/origin/<branch>` because it matches the remote's default
    // fetch refspec, without the non-determinism of pulling in unrelated
    // branch/tag churn.
    runner
        .run(&["fetch", "--end-of-options", "origin", &branch])
        .map_err(|e| {
            lock.release();
            format!("git fetch: {e}")
        })?;

    // The OID this call's own fetch just observed for the remote branch.
    // This — NOT local HEAD — is what a `--force-with-lease` must assert the
    // remote still is: local HEAD is by construction different from (ahead
    // of) the remote whenever a lease is about to be used, so leasing
    // against local HEAD is not a race-only failure, it is a guaranteed
    // "stale info" rejection on every single push (confirmed live: pushing
    // with `--force-with-lease=<branch>:<local HEAD>` against a real ahead
    // fixture is rejected 100% of the time; leasing against the fetched
    // `origin/<branch>` oid instead succeeds). This is what makes the lease
    // airtight per the one-call design: the expectation comes from a fetch
    // this very call performed, never from a value the caller transcribed.
    let upstream_oid = runner
        .run_opt(&["rev-parse", &upstream])
        .map(|o| String::from_utf8_lossy(&o).trim().to_string())
        .unwrap_or_default();

    if let Some(hook) = pre_push_hook.as_mut() {
        hook();
    }

    // Classify with rev-list --left-right --count.
    let (ahead, behind) = classify_counts(&runner, &upstream);

    let merge_base = runner
        .run_opt(&["merge-base", "HEAD", &upstream])
        .map(|o| String::from_utf8_lossy(&o).trim().to_string())
        .unwrap_or_default();

    let state = classify_state(ahead, behind);

    let result = match state {
        "up_to_date" => {
            json!({
                "state": "up_to_date",
                "head": head,
                "branch": branch,
                "upstream": upstream,
            })
        }
        "fast_forward" => {
            // update's guard suite: refuse if incoming changes intersect
            // dirty paths that would be silently overwritten. Uses
            // `status_porcelain_or_err`/`diff_name_status_or_err`, NOT
            // their lenient counterparts: an undetermined status or
            // changed-path set must abort the fast-forward, never be
            // silently read as "nothing is dirty"/"nothing changed" — that
            // would let `git merge --ff-only` overwrite a genuinely dirty
            // file with no way for the caller to have known.
            // Deliberately NOT `dirty_excluding_sidecar`: this gate only
            // refuses on the INTERSECTION of dirty paths with the tracked
            // paths the fast-forward would change, so untracked sidecar
            // entries can never block it — filtering would be redundant.
            let dirty = runner.status_porcelain_or_err().map_err(|e| {
                lock.release();
                format!("could not determine working-tree status, refusing to fast-forward: {e}")
            })?;
            if !dirty.is_empty() {
                let changes = runner
                    .diff_name_status_or_err(&head, &upstream)
                    .map_err(|e| {
                        lock.release();
                        format!(
                            "could not determine which paths the fast-forward would change, \
                         refusing to proceed while dirty files are present: {e}"
                        )
                    })?;
                let changed_paths: std::collections::HashSet<String> =
                    changes.iter().map(|(_, p)| p.clone()).collect();
                let dirty_intersect: Vec<String> = dirty
                    .iter()
                    .filter(|(_, p)| changed_paths.contains(p))
                    .map(|(_, p)| p.clone())
                    .collect();
                if !dirty_intersect.is_empty() {
                    lock.release();
                    return Err(format!(
                        "UNSUPPORTED_STATE: dirty files would be overwritten: {}",
                        dirty_intersect.join(", ")
                    ));
                }
            }
            // Fast-forward. `--ff-only` guarantees this can never fabricate
            // a merge commit.
            runner
                .run(&["merge", "--ff-only", &upstream])
                .map_err(|e| {
                    lock.release();
                    format!("git merge --ff-only: {e}")
                })?;
            json!({
                "state": "fast_forwarded",
                "from": head,
                "to": runner.rev_parse_head().unwrap_or_default(),
                "branch": branch,
            })
        }
        "ahead" => {
            if push_mode == "auto" {
                match attempt_lease_push_or_reclassify(&runner, &branch, &upstream_oid, &upstream) {
                    LeaseOutcome::Pushed => json!({
                        "state": "pushed",
                        "head": head,
                        "branch": branch,
                    }),
                    LeaseOutcome::Raced {
                        error,
                        ahead: a2,
                        behind: b2,
                    } => json!({
                        "state": "push_raced",
                        "head": head,
                        "branch": branch,
                        "push_error": error,
                        "reclassified": {
                            "ahead": a2,
                            "behind": b2,
                            "state": classify_state(a2, b2),
                        },
                        "next": "remote advanced during push; call reconcile again",
                    }),
                }
            } else {
                json!({
                    "state": "ahead",
                    "head": head,
                    "branch": branch,
                    "ahead": ahead,
                })
            }
        }
        "diverged" => {
            if !git_supports_merge_tree_write_tree(root) {
                json!({
                    "state": "diverged",
                    "merge_base": merge_base,
                    "ahead": ahead,
                    "behind": behind,
                    "clean_rebase_possible": false,
                    "feature_unavailable": true,
                    "conflicts": [],
                    "non_conflicting": non_conflicting_paths(root, &merge_base, &head, &upstream),
                    "backup_ref": Value::Null,
                    "next": "git >= 2.38 required for merge-tree; conflict detail and rebase-if-clean are unavailable on this git",
                })
            } else {
                let probe = probe_merge_tree(root, &head, &upstream);

                if opts.strategy == "rebase-if-clean" {
                    // Clean worktree required as precondition. Uses
                    // `status_porcelain_or_err`: an undetermined status must
                    // abort, never be silently read as "clean" — that would
                    // let a rebase run against a dirty worktree it was
                    // specifically gated to never touch. Pixel's own `.pixel/`
                    // sidecar is excluded: it is never tracked, never touched
                    // by rebase, and regenerated by the daemon — without this
                    // exclusion the daemon's own writes would block every call.
                    let dirty = dirty_excluding_sidecar(
                        &runner,
                        "could not determine working-tree status, refusing rebase-if-clean",
                    )
                    .inspect_err(|_| {
                        lock.release();
                    })?;
                    if !dirty.is_empty() {
                        lock.release();
                        return Err(format!(
                            "UNSUPPORTED_STATE: rebase-if-clean requires clean worktree, {} dirty files",
                            dirty.len()
                        ));
                    }

                    // Backup ref written FIRST, before any attempt to touch
                    // the worktree.
                    let backup_ref = format!("refs/pixel/reconcile-backup/{branch}");
                    runner
                        .run(&["update-ref", &backup_ref, &head])
                        .map_err(|e| {
                            lock.release();
                            format!("git update-ref (backup): {e}")
                        })?;

                    if !probe.clean {
                        // merge-tree predicts conflicts. Attempt the rebase
                        // anyway — if it conflicts, auto-resolve the conflict
                        // markers by union-merging both sides, then continue.
                        // This handles additive conflicts (both sides added
                        // different content to the same region) which are the
                        // common case in collaborative development.
                        match runner.run(&["rebase", &upstream]) {
                            Ok(_) => {
                                // Rebase succeeded cleanly (merge-tree
                                // was overly cautious).
                                let new_head = runner.rev_parse_head().unwrap_or_default();
                                clear_conflict_state(root);
                                if push_mode == "auto" {
                                    match attempt_lease_push_or_reclassify(
                                        &runner,
                                        &branch,
                                        &upstream_oid,
                                        &upstream,
                                    ) {
                                        LeaseOutcome::Pushed => json!({
                                            "state": "rebased",
                                            "from": head,
                                            "to": new_head,
                                            "branch": branch,
                                            "backup_ref": backup_ref,
                                            "pushed": true,
                                        }),
                                        LeaseOutcome::Raced {
                                            error,
                                            ahead: a2,
                                            behind: b2,
                                        } => json!({
                                            "state": "rebased",
                                            "from": head,
                                            "to": new_head,
                                            "branch": branch,
                                            "backup_ref": backup_ref,
                                            "pushed": false,
                                            "push_error": error,
                                            "reclassified": {
                                                "ahead": a2,
                                                "behind": b2,
                                                "state": classify_state(a2, b2),
                                            },
                                            "next": "local rebase succeeded but remote advanced during push; call reconcile again",
                                        }),
                                    }
                                } else {
                                    json!({
                                        "state": "rebased",
                                        "from": head,
                                        "to": new_head,
                                        "branch": branch,
                                        "backup_ref": backup_ref,
                                        "pushed": false,
                                    })
                                }
                            }
                            Err(_) => {
                                // Rebase conflicted. Auto-resolve the conflict
                                // markers in the worktree, then continue.
                                let unmerged = runner
                                    .run_opt(&["diff", "--name-only", "--diff-filter=U"])
                                    .map(|b| {
                                        String::from_utf8_lossy(&b)
                                            .lines()
                                            .map(String::from)
                                            .collect::<Vec<_>>()
                                    })
                                    .unwrap_or_default();
                                let mut rebase_resolved = Vec::new();
                                let mut rebase_unresolved = Vec::new();
                                for path in &unmerged {
                                    if auto_resolve_conflict_markers(&runner, root, path) {
                                        let _ = runner.run(&["add", path]);
                                        rebase_resolved.push(path.clone());
                                    } else {
                                        rebase_unresolved.push(path.clone());
                                    }
                                }

                                if rebase_unresolved.is_empty() && !rebase_resolved.is_empty() {
                                    // All rebase conflicts auto-resolved.
                                    if continue_rebase(&runner) {
                                        let new_head = runner.rev_parse_head().unwrap_or_default();
                                        clear_conflict_state(root);
                                        if push_mode == "auto" {
                                            match attempt_lease_push_or_reclassify(
                                                &runner,
                                                &branch,
                                                &upstream_oid,
                                                &upstream,
                                            ) {
                                                LeaseOutcome::Pushed => json!({
                                                    "state": "rebased",
                                                    "from": head,
                                                    "to": new_head,
                                                    "branch": branch,
                                                    "backup_ref": backup_ref,
                                                    "pushed": true,
                                                    "auto_resolved": rebase_resolved,
                                                }),
                                                LeaseOutcome::Raced {
                                                    error,
                                                    ahead: a2,
                                                    behind: b2,
                                                } => json!({
                                                    "state": "rebased",
                                                    "from": head,
                                                    "to": new_head,
                                                    "branch": branch,
                                                    "backup_ref": backup_ref,
                                                    "pushed": false,
                                                    "push_error": error,
                                                    "auto_resolved": rebase_resolved,
                                                    "reclassified": {
                                                        "ahead": a2,
                                                        "behind": b2,
                                                        "state": classify_state(a2, b2),
                                                    },
                                                    "next": "local rebase succeeded but remote advanced during push; call reconcile again",
                                                }),
                                            }
                                        } else {
                                            json!({
                                                "state": "rebased",
                                                "from": head,
                                                "to": new_head,
                                                "branch": branch,
                                                "backup_ref": backup_ref,
                                                "pushed": false,
                                                "auto_resolved": rebase_resolved,
                                            })
                                        }
                                    } else {
                                        // --continue failed, abort and report.
                                        safe_rebase_abort(&runner);
                                        let report = build_conflict_report(
                                            &runner,
                                            &merge_base,
                                            &head,
                                            &upstream,
                                            &probe,
                                        );
                                        let conflict_count =
                                            report["conflict_count"].as_u64().unwrap_or(0) as usize;
                                        write_conflict_state(root, conflict_count);
                                        json!({
                                            "state": "diverged",
                                            "merge_base": merge_base,
                                            "ahead": ahead,
                                            "behind": behind,
                                            "clean_rebase_possible": false,
                                            "conflicts": report["conflicts"],
                                            "conflict_count": report["conflict_count"],
                                            "report_truncated": report["report_truncated"],
                                            "non_conflicting": non_conflicting_paths(root, &merge_base, &head, &upstream),
                                            "backup_ref": backup_ref,
                                            "auto_resolved": rebase_resolved,
                                            "next": "manual resolution required (rebase --continue failed)",
                                        })
                                    }
                                } else {
                                    // Some rebase conflicts couldn't be auto-resolved.
                                    safe_rebase_abort(&runner);
                                    let report = build_conflict_report(
                                        &runner,
                                        &merge_base,
                                        &head,
                                        &upstream,
                                        &probe,
                                    );
                                    let conflict_count =
                                        report["conflict_count"].as_u64().unwrap_or(0) as usize;
                                    write_conflict_state(root, conflict_count);
                                    json!({
                                        "state": "diverged",
                                        "merge_base": merge_base,
                                        "ahead": ahead,
                                        "behind": behind,
                                        "clean_rebase_possible": false,
                                        "conflicts": report["conflicts"],
                                        "conflict_count": report["conflict_count"],
                                        "report_truncated": report["report_truncated"],
                                        "non_conflicting": non_conflicting_paths(root, &merge_base, &head, &upstream),
                                        "backup_ref": backup_ref,
                                        "auto_resolved": rebase_resolved,
                                        "auto_unresolved": rebase_unresolved,
                                        "next": "manual resolution required",
                                    })
                                }
                            }
                        }
                    } else {
                        // Non-interactive linear rebase under journal. Plain
                        // `git rebase` never fabricates a merge commit.
                        match runner.run(&["rebase", &upstream]) {
                            Ok(_) => {
                                let new_head = runner.rev_parse_head().unwrap_or_default();
                                if push_mode == "auto" {
                                    // Lease against `upstream_oid`, not
                                    // `new_head`: the rebase only rewrote
                                    // local history, the remote is still at
                                    // the OID this call fetched earlier.
                                    match attempt_lease_push_or_reclassify(
                                        &runner,
                                        &branch,
                                        &upstream_oid,
                                        &upstream,
                                    ) {
                                        LeaseOutcome::Pushed => json!({
                                            "state": "rebased",
                                            "from": head,
                                            "to": new_head,
                                            "branch": branch,
                                            "backup_ref": backup_ref,
                                            "pushed": true,
                                        }),
                                        LeaseOutcome::Raced {
                                            error,
                                            ahead: a2,
                                            behind: b2,
                                        } => json!({
                                            "state": "rebased",
                                            "from": head,
                                            "to": new_head,
                                            "branch": branch,
                                            "backup_ref": backup_ref,
                                            "pushed": false,
                                            "push_error": error,
                                            "reclassified": {
                                                "ahead": a2,
                                                "behind": b2,
                                                "state": classify_state(a2, b2),
                                            },
                                            "next": "local rebase succeeded but remote advanced during push; call reconcile again",
                                        }),
                                    }
                                } else {
                                    json!({
                                        "state": "rebased",
                                        "from": head,
                                        "to": new_head,
                                        "branch": branch,
                                        "backup_ref": backup_ref,
                                        "pushed": false,
                                    })
                                }
                            }
                            Err(e) => {
                                // Surprise conflict despite a clean merge-tree
                                // prediction. Capture the actual unmerged
                                // paths from the mid-rebase index BEFORE
                                // aborting — this is the only window they're
                                // observable in, since `rebase --abort`
                                // restores the clean pre-rebase worktree.
                                let unmerged: Vec<String> = runner
                                    .status_porcelain()
                                    .into_iter()
                                    .filter(|(xy, _)| xy.contains('U') || xy == "AA" || xy == "DD")
                                    .map(|(_, p)| p)
                                    .collect();
                                // Never leave the repo mid-rebase.
                                safe_rebase_abort(&runner);
                                json!({
                                    "state": "diverged",
                                    "merge_base": merge_base,
                                    "ahead": ahead,
                                    "behind": behind,
                                    "clean_rebase_possible": true,
                                    "rebase_aborted": true,
                                    "error": e.to_string(),
                                    "unmerged_paths_at_abort": unmerged,
                                    "non_conflicting": non_conflicting_paths(root, &merge_base, &head, &upstream),
                                    "backup_ref": backup_ref,
                                    "next": "manual rebase required",
                                })
                            }
                        }
                    }
                } else {
                    // Default: report only, no mutation.
                    let report = if probe.clean {
                        json!({"conflicts": [], "conflict_count": 0, "report_truncated": false})
                    } else {
                        build_conflict_report(&runner, &merge_base, &head, &upstream, &probe)
                    };
                    json!({
                        "state": "diverged",
                        "merge_base": merge_base,
                        "ahead": ahead,
                        "behind": behind,
                        "clean_rebase_possible": probe.clean,
                        "conflicts": report["conflicts"],
                        "conflict_count": report["conflict_count"],
                        "report_truncated": report["report_truncated"],
                        "non_conflicting": non_conflicting_paths(root, &merge_base, &head, &upstream),
                        "backup_ref": Value::Null,
                        "next": "use strategy=rebase-if-clean to auto-rebase",
                    })
                }
            }
        }
        _ => json!({"state": "unknown"}),
    };

    journal.complete(&request_id, &repo_key, result.clone())?;
    lock.release();
    Ok(result)
}

/// `--into <target>` integration: rebase the current (feature) branch onto
/// `origin/<target>`, then fast-forward the LOCAL `<target>` branch ref to
/// the rebased feature head. Never a merge commit; the target ref only ever
/// moves fast-forward (CAS `update-ref <ref> <new> <old>`, safe because the
/// target is by precondition not the checked-out branch).
///
/// Refusal order is deliberate — every structured refusal happens BEFORE any
/// mutation:
///   1. target == current branch / detached HEAD → UNSUPPORTED_STATE.
///   2. local `<target>` missing → UNSUPPORTED_STATE.
///   3. strict fetch of the remote target (the rebase base must be fresh).
///   4. local `<target>` not an ancestor of `origin/<target>` →
///      NON_FAST_FORWARD (the post-rebase ff would be a forced move).
///   5. dirty worktree → UNSUPPORTED_STATE (same rule as rebase-if-clean).
///   6. merge-tree predicts conflicts → diverged report naming the target,
///      no rebase attempted.
///
/// Only once all of those pass does the rebase run; the ff of `<target>` is
/// then guaranteed (target_old ≤ origin/<target> ≤ rebased head).
///
/// On success the caller (reconcile_with_hooks) journals and releases the
/// lock; on error this function releases the lock itself, matching the
/// file-wide error-path convention.
fn reconcile_into(
    root: &Path,
    runner: &GitRunner,
    lock: &mut RepositoryLock,
    head: &str,
    branch: &str,
    target: &str,
    push_mode: &str,
) -> Result<Value, String> {
    if branch == "HEAD" {
        lock.release();
        return Err(
            "UNSUPPORTED_STATE: detached HEAD; --into requires a checked-out feature branch"
                .to_string(),
        );
    }
    if branch == target {
        lock.release();
        return Err(format!(
            "UNSUPPORTED_STATE: --into target {target:?} is the currently checked-out branch; \
             check out the feature branch and name the integration target"
        ));
    }

    // Local target must exist — --into fast-forwards it, it never creates it.
    let target_ref = format!("refs/heads/{target}");
    let target_old_oid = runner
        .run_opt(&["rev-parse", "--verify", "--quiet", &target_ref])
        .map(|o| String::from_utf8_lossy(&o).trim().to_string())
        .filter(|s| !s.is_empty());
    let Some(target_old_oid) = target_old_oid else {
        lock.release();
        return Err(format!(
            "UNSUPPORTED_STATE: local branch {target:?} does not exist; --into fast-forwards \
             the local target branch, so it must already exist locally"
        ));
    };

    // Strict fetch of the remote target: the rebase base is origin/<target>
    // and must be fresh — a stale base makes the whole integration stale.
    runner
        .run(&["fetch", "--end-of-options", "origin", target])
        .map_err(|e| {
            lock.release();
            format!("git fetch origin {target}: {e}")
        })?;
    // Tolerant fetch of the feature branch: it may not exist on the remote
    // yet. Its freshly-observed OID (or absence — an empty lease expectation
    // means "the remote ref must not exist") feeds the leased push below.
    let _ = runner.run(&["fetch", "--end-of-options", "origin", branch]);

    let remote_target = format!("origin/{target}");
    let remote_target_oid = runner
        .run_opt(&["rev-parse", &remote_target])
        .map(|o| String::from_utf8_lossy(&o).trim().to_string())
        .unwrap_or_default();
    if remote_target_oid.is_empty() {
        lock.release();
        return Err(format!(
            "UNSUPPORTED_STATE: {remote_target} not found after fetch; --into rebases onto the \
             remote-tracking target, which must exist"
        ));
    }

    let upstream_oid = runner
        .run_opt(&["rev-parse", &format!("origin/{branch}")])
        .map(|o| String::from_utf8_lossy(&o).trim().to_string())
        .unwrap_or_default();

    // ff precondition, checked BEFORE any mutation: the local target must be
    // an ancestor of (or equal to) origin/<target>. The rebased head will sit
    // atop origin/<target>, so this is exactly the condition under which the
    // later target move is a pure fast-forward. A diverged local target must
    // be reconciled on its own first — never forced, never merged.
    let target_is_ancestor = runner
        .run_opt(&[
            "merge-base",
            "--is-ancestor",
            &target_old_oid,
            &remote_target_oid,
        ])
        .is_some();
    if !target_is_ancestor {
        lock.release();
        return Err(format!(
            "NON_FAST_FORWARD: local branch {target:?} ({target_old_oid}) is not an ancestor of \
             {remote_target} ({remote_target_oid}); refusing to move it — never force, never \
             merge. Reconcile {target:?} itself first, then retry --into"
        ));
    }

    // Clean worktree required — identical rule to the rebase-if-clean path,
    // same fail-closed status source. Pixel's own `.pixel/` sidecar is
    // excluded (see `rebase-if-clean` comment for rationale).
    let dirty = dirty_excluding_sidecar(
        runner,
        "could not determine working-tree status, refusing --into integration",
    )
    .inspect_err(|_| {
        lock.release();
    })?;
    if !dirty.is_empty() {
        lock.release();
        return Err(format!(
            "UNSUPPORTED_STATE: --into requires a clean worktree, {} dirty files",
            dirty.len()
        ));
    }

    let merge_base = runner
        .run_opt(&["merge-base", "HEAD", &remote_target])
        .map(|o| String::from_utf8_lossy(&o).trim().to_string())
        .unwrap_or_default();

    if !git_supports_merge_tree_write_tree(root) {
        // Same gate as plain diverged handling: without merge-tree the clean
        // rebase cannot be proven, so nothing is mutated.
        return Ok(json!({
            "state": "diverged",
            "into_target": target,
            "merge_base": merge_base,
            "clean_rebase_possible": false,
            "feature_unavailable": true,
            "conflicts": [],
            "non_conflicting": non_conflicting_paths(root, &merge_base, head, &remote_target),
            "backup_ref": Value::Null,
            "next": "git >= 2.38 required for merge-tree; --into integration is unavailable on this git",
        }));
    }

    // Backup ref written FIRST, before any attempt to touch the worktree.
    let backup_ref = format!("refs/pixel/reconcile-backup/{branch}");
    runner
        .run(&["update-ref", &backup_ref, head])
        .map_err(|e| {
            lock.release();
            format!("git update-ref (backup): {e}")
        })?;

    let probe = probe_merge_tree(root, head, &remote_target);
    if !probe.clean {
        // merge-tree predicts conflicts. Attempt the rebase anyway — if it
        // conflicts, auto-resolve conflict markers by union-merging both
        // sides, then continue. Same approach as the plain diverged path.
        match runner.run(&["rebase", &remote_target]) {
            Ok(_) => {
                let new_head = runner.rev_parse_head().unwrap_or_default();
                clear_conflict_state(root);
                return Ok(json!({
                    "state": "rebased",
                    "into_target": target,
                    "from": head,
                    "to": new_head,
                    "backup_ref": backup_ref,
                }));
            }
            Err(_) => {
                let unmerged = runner
                    .run_opt(&["diff", "--name-only", "--diff-filter=U"])
                    .map(|b| {
                        String::from_utf8_lossy(&b)
                            .lines()
                            .map(String::from)
                            .collect::<Vec<_>>()
                    })
                    .unwrap_or_default();
                let mut rebase_resolved = Vec::new();
                let mut rebase_unresolved = Vec::new();
                for path in &unmerged {
                    if auto_resolve_conflict_markers(runner, root, path) {
                        let _ = runner.run(&["add", path]);
                        rebase_resolved.push(path.clone());
                    } else {
                        rebase_unresolved.push(path.clone());
                    }
                }

                if rebase_unresolved.is_empty()
                    && !rebase_resolved.is_empty()
                    && continue_rebase(runner)
                {
                    let new_head = runner.rev_parse_head().unwrap_or_default();
                    clear_conflict_state(root);
                    return Ok(json!({
                        "state": "rebased",
                        "into_target": target,
                        "from": head,
                        "to": new_head,
                        "backup_ref": backup_ref,
                        "auto_resolved": rebase_resolved,
                    }));
                }
                // Fall back to manual.
                safe_rebase_abort(runner);
                let report =
                    build_conflict_report(runner, &merge_base, head, &remote_target, &probe);
                let conflict_count = report["conflict_count"].as_u64().unwrap_or(0) as usize;
                write_conflict_state(root, conflict_count);
                return Ok(json!({
                    "state": "diverged",
                    "into_target": target,
                    "merge_base": merge_base,
                    "clean_rebase_possible": false,
                    "conflicts": report["conflicts"],
                    "conflict_count": report["conflict_count"],
                    "report_truncated": report["report_truncated"],
                    "non_conflicting": non_conflicting_paths(root, &merge_base, head, &remote_target),
                    "backup_ref": backup_ref,
                    "auto_resolved": rebase_resolved,
                    "auto_unresolved": rebase_unresolved,
                    "next": format!("manual resolution required before integrating into {target:?}"),
                }));
            }
        }
    }

    // Non-interactive linear rebase onto the remote-tracking target. Plain
    // `git rebase` never fabricates a merge commit.
    if let Err(e) = runner.run(&["rebase", &remote_target]) {
        // Surprise conflict despite a clean merge-tree prediction — capture
        // the unmerged paths from the mid-rebase index BEFORE aborting (the
        // only window they're observable in), then abort. Target untouched.
        let unmerged: Vec<String> = runner
            .status_porcelain()
            .into_iter()
            .filter(|(xy, _)| xy.contains('U') || xy == "AA" || xy == "DD")
            .map(|(_, p)| p)
            .collect();
        safe_rebase_abort(runner);
        return Ok(json!({
            "state": "diverged",
            "into_target": target,
            "merge_base": merge_base,
            "clean_rebase_possible": true,
            "rebase_aborted": true,
            "error": e.to_string(),
            "unmerged_paths_at_abort": unmerged,
            "non_conflicting": non_conflicting_paths(root, &merge_base, head, &remote_target),
            "backup_ref": backup_ref,
            "next": "manual rebase required",
        }));
    }
    let new_head = runner.rev_parse_head().unwrap_or_default();

    // Fast-forward the LOCAL target ref to the rebased head. CAS update-ref
    // (<new> <old>) is safe while the target is not checked out (guaranteed:
    // the current branch is the feature) and refuses if anything moved the
    // target under us — though the repository lock already excludes that.
    // Ancestry holds by construction: target_old ≤ origin/<target> ≤ new_head.
    runner
        .run(&["update-ref", &target_ref, &new_head, &target_old_oid])
        .map_err(|e| {
            lock.release();
            format!("git update-ref {target_ref}: {e}")
        })?;

    // Push per push mode: feature with a lease against this call's own
    // freshly-fetched origin/<branch> OID (same rationale as the plain
    // rebased path), target as a plain ff push (its move IS a fast-forward
    // of the remote target by construction; no force of any kind).
    let (feature_pushed, feature_push_error, target_pushed, target_push_error) =
        if push_mode == "auto" {
            let lease_arg = format!("--force-with-lease={branch}:{upstream_oid}");
            let f = runner.run(&["push", &lease_arg, "origin", branch]);
            let refspec = format!("{target}:refs/heads/{target}");
            let t = runner.run(&["push", "origin", &refspec]);
            (
                f.is_ok(),
                f.err().map(|e| e.to_string()),
                t.is_ok(),
                t.err().map(|e| e.to_string()),
            )
        } else {
            (false, None, false, None)
        };

    Ok(json!({
        "state": "integrated",
        "branch": branch,
        "from": head,
        "to": new_head,
        "backup_ref": backup_ref,
        "pushed": feature_pushed,
        "push_error": feature_push_error,
        "into": {
            "target": target,
            "target_old_oid": target_old_oid,
            "target_new_oid": new_head,
            "target_pushed": target_pushed,
            "target_push_error": target_push_error,
        },
    }))
}

fn classify_counts(runner: &GitRunner, upstream: &str) -> (u64, u64) {
    let counts = runner.run_opt(&[
        "rev-list",
        "--left-right",
        "--count",
        &format!("HEAD...{upstream}"),
    ]);
    match counts {
        Some(out) => {
            let s = String::from_utf8_lossy(&out).trim().to_string();
            let parts: Vec<&str> = s.split_whitespace().collect();
            if parts.len() == 2 {
                (
                    parts[0].parse::<u64>().unwrap_or(0),
                    parts[1].parse::<u64>().unwrap_or(0),
                )
            } else {
                (0, 0)
            }
        }
        None => (0, 0),
    }
}

fn classify_state(ahead: u64, behind: u64) -> &'static str {
    match (ahead, behind) {
        (0, 0) => "up_to_date",
        (0, _) => "fast_forward",
        (_, 0) => "ahead",
        (_, _) => "diverged",
    }
}

enum LeaseOutcome {
    Pushed,
    Raced {
        error: String,
        ahead: u64,
        behind: u64,
    },
}

/// Leased push with `--force-with-lease=<branch>:<lease_oid>`, where
/// `lease_oid` is the OID *this call's own fetch* just observed — the
/// one-call design makes the lease airtight (no separately-transcribed OID
/// that could go stale between a caller's read and its push).
///
/// On any push failure (most commonly the remote having moved since our
/// fetch, i.e. a lease rejection), this performs exactly ONE re-fetch of the
/// branch plus one reclassification and returns that as data — it never
/// retries the push itself. A second blind retry is exactly the failure mode
/// this function exists to rule out.
fn attempt_lease_push_or_reclassify(
    runner: &GitRunner,
    branch: &str,
    lease_oid: &str,
    upstream: &str,
) -> LeaseOutcome {
    let lease_arg = format!("--force-with-lease={branch}:{lease_oid}");
    match runner.run(&["push", &lease_arg, "origin", branch]) {
        Ok(_) => LeaseOutcome::Pushed,
        Err(e) => {
            let _ = runner.run(&["fetch", "--end-of-options", "origin", branch]);
            let (a2, b2) = classify_counts(runner, upstream);
            LeaseOutcome::Raced {
                error: e.to_string(),
                ahead: a2,
                behind: b2,
            }
        }
    }
}

/// `git --version` >= 2.38 gate for `merge-tree --write-tree` (the "real
/// merge" mode this op depends on for in-memory conflict prediction). Older
/// git either lacks `--write-tree` entirely or predates its stabilized
/// output format, so callers must not attempt to interpret its output.
#[cfg_attr(test, mutants::skip)] // one-line adapter over the real git; `-> true` is what a modern git answers, the parsing is tested below
fn git_supports_merge_tree_write_tree(root: &Path) -> bool {
    GitRunner::new(root)
        .run(&["--version"])
        .is_ok_and(|out| version_supports_merge_tree_write_tree(&String::from_utf8_lossy(&out)))
}

/// The pure half of [`git_supports_merge_tree_write_tree`]: `git --version`
/// output ("git version 2.55.0", possibly with a vendor/build suffix) is
/// at least 2.38.
fn version_supports_merge_tree_write_tree(version_line: &str) -> bool {
    let Some(ver_field) = version_line.split_whitespace().nth(2) else {
        return false;
    };
    let mut parts = ver_field.split('.');
    let Some(major) = parts.next().and_then(|p| p.parse::<u32>().ok()) else {
        return false;
    };
    let minor = parts
        .next()
        .and_then(|p| p.parse::<u32>().ok())
        .unwrap_or(0);
    (major, minor) >= (2, 38)
}

#[derive(Debug)]
struct MergeTreeProbe {
    /// True iff `merge-tree --write-tree` exited 0 (no textual conflicts).
    clean: bool,
    /// Raw stdout of `merge-tree --write-tree --no-messages <ours> <theirs>`
    /// — tree oid line, then (if conflicted) one `<mode> <oid> <stage>\t<path>`
    /// line per conflicted stage entry.
    stage_lines: String,
    /// Raw stdout of `merge-tree --write-tree <ours> <theirs>` (messages
    /// included) — used to recover human-readable `CONFLICT (<kind>): ...`
    /// text per path.
    messages: String,
}

/// Runs `git merge-tree --write-tree` through `GitRunner::run_output`, never
/// `run`/`run_opt`: `merge-tree` exits 1 (not 0) precisely when there ARE
/// conflicts, and those two discard stdout on any non-zero exit. An earlier
/// version of this probe went through `run_opt` and so observed `None` on
/// the exact inputs it most needed to inspect, reporting every real
/// conflict as an empty list — the defect class PLAN.md calls out (`review`'s
/// `!conflicted` filtering). Stdout is kept whatever the status and the
/// verdict is keyed off the real exit code; the runner adds the timeout and
/// the enumeration-sized output cap a bare `std::process::Command` lacked.
fn probe_merge_tree(root: &Path, ours: &str, theirs: &str) -> MergeTreeProbe {
    let runner =
        GitRunner::new(root).with_max_output_bytes(Some(pixel_git::ENUMERATION_MAX_OUTPUT_BYTES));
    let run = |extra: &[&str]| -> (bool, String) {
        let mut args = vec!["merge-tree", "--write-tree"];
        args.extend_from_slice(extra);
        args.push(ours);
        args.push(theirs);
        match runner.run_output(&args, &[]) {
            Ok(out) => (
                out.success(),
                String::from_utf8_lossy(&out.stdout).into_owned(),
            ),
            Err(_) => (false, String::new()),
        }
    };
    let (clean, stage_lines) = run(&["--no-messages"]);
    let (_, messages) = run(&[]);
    MergeTreeProbe {
        clean,
        stage_lines,
        messages,
    }
}

/// Parses `merge-tree --write-tree --no-messages` stdout into
/// `path -> (stage -> oid)`. Stage 1 = merge base, 2 = ours, 3 = theirs; a
/// missing stage means that side has no version of the path (e.g. add/add
/// conflicts have no stage 1, modify/delete conflicts have no stage 3 when
/// the file was deleted on the "theirs" side).
fn parse_stage_lines(text: &str) -> BTreeMap<String, BTreeMap<u8, String>> {
    let mut map: BTreeMap<String, BTreeMap<u8, String>> = BTreeMap::new();
    for line in text.lines().skip(1) {
        // skip the leading tree-oid line
        if line.is_empty() {
            continue;
        }
        let mut parts = line.splitn(2, '\t');
        let Some(meta) = parts.next() else { continue };
        let Some(path) = parts.next() else { continue };
        let mut fields = meta.split_whitespace();
        let Some(_mode) = fields.next() else { continue };
        let Some(oid) = fields.next() else { continue };
        let Some(stage) = fields.next().and_then(|s| s.parse::<u8>().ok()) else {
            continue;
        };
        map.entry(path.to_string())
            .or_default()
            .insert(stage, oid.to_string());
    }
    map
}

/// Parses `CONFLICT (<kind>): <message>` lines out of merge-tree's
/// informational message section.
fn parse_conflict_kinds(text: &str) -> Vec<(String, String)> {
    text.lines()
        .filter_map(|l| {
            let l = l.trim();
            let rest = l.strip_prefix("CONFLICT (")?;
            let idx = rest.find(')')?;
            let kind = rest[..idx].to_string();
            let msg = rest[idx + 1..].trim_start_matches(':').trim().to_string();
            Some((kind, msg))
        })
        .collect()
}

/// Truncates `s` to at most `cap` bytes on a UTF-8 char boundary, reporting
/// whether truncation happened.
fn capped(mut s: String, cap: usize) -> (String, bool) {
    if s.len() <= cap {
        return (s, false);
    }
    s.truncate(cap);
    while !s.is_char_boundary(s.len()) {
        s.pop();
    }
    (s, true)
}

/// `git diff --unified=0 <merge_base> <side_ref> -- <path>`, capped at
/// `HUNK_MAX_BYTES`. `None` when there is no merge base (unrelated
/// histories) or the diff could not be produced.
fn side_hunk(
    runner: &GitRunner,
    merge_base: &str,
    side_ref: &str,
    path: &str,
) -> (Option<String>, bool) {
    if merge_base.is_empty() {
        return (None, false);
    }
    match runner.run_opt(&[
        "diff",
        "--no-color",
        "--unified=0",
        merge_base,
        side_ref,
        "--",
        path,
    ]) {
        Some(bytes) => {
            let (text, truncated) =
                capped(String::from_utf8_lossy(&bytes).into_owned(), HUNK_MAX_BYTES);
            (Some(text), truncated)
        }
        None => (None, false),
    }
}

/// Extracts the base-side span (`"<start>,<count>"`) from a hunk's
/// `@@ -a,b +c,d @@` header, if present.
fn extract_base_span(hunk: &Option<String>) -> Option<String> {
    let h = hunk.as_ref()?;
    for line in h.lines() {
        if let Some(rest) = line.strip_prefix("@@ -")
            && let Some(end) = rest.find(" +")
        {
            return Some(rest[..end].to_string());
        }
    }
    None
}

/// Builds the full conflict report — this is the fix for the known defect
/// class in the predecessor tool's `review` op, which silently filtered
/// conflicted paths out of its response. Every path merge-tree reports as
/// conflicted MUST be present here, with per-side oid/hunk detail and a
/// parsed `conflict_kind`, capped per-path (`HUNK_MAX_BYTES`) and in total
/// (`REPORT_MAX_BYTES`) with truncation flagged rather than silently dropped.
fn build_conflict_report(
    runner: &GitRunner,
    merge_base: &str,
    head: &str,
    upstream: &str,
    probe: &MergeTreeProbe,
) -> Value {
    let stage_map = parse_stage_lines(&probe.stage_lines);
    let kinds = parse_conflict_kinds(&probe.messages);

    let mut conflicts = Vec::new();
    let mut total_bytes = 0usize;
    let mut report_truncated = false;

    for (path, stages) in &stage_map {
        if total_bytes >= REPORT_MAX_BYTES {
            report_truncated = true;
            break;
        }
        let base_oid = stages.get(&1).cloned();
        let ours_oid = stages.get(&2).cloned();
        let theirs_oid = stages.get(&3).cloned();

        let (ours_hunk, ours_truncated) = side_hunk(runner, merge_base, head, path);
        let (theirs_hunk, theirs_truncated) = side_hunk(runner, merge_base, upstream, path);
        let base_span = extract_base_span(&ours_hunk).or_else(|| extract_base_span(&theirs_hunk));

        let conflict_kind = kinds
            .iter()
            .find(|(_, msg)| msg.contains(path.as_str()))
            .map_or_else(|| "content".to_string(), |(k, _)| k.clone());

        let entry = json!({
            "path": path,
            "conflict_kind": conflict_kind,
            "base_span": base_span,
            "base_oid": base_oid,
            "ours": {
                "oid": ours_oid,
                "hunk": ours_hunk,
                "hunk_truncated": ours_truncated,
            },
            "theirs": {
                "oid": theirs_oid,
                "hunk": theirs_hunk,
                "hunk_truncated": theirs_truncated,
            },
        });
        total_bytes = total_bytes.saturating_add(entry.to_string().len());
        conflicts.push(entry);
    }

    json!({
        "conflicts": conflicts,
        "conflict_count": stage_map.len(),
        "report_truncated": report_truncated,
    })
}

/// Paths changed on exactly one side *relative to the merge base* — a path
/// changed on both sides isn't "non-conflicting" (it's either a real
/// conflict, tracked separately in `conflicts`, or coincidentally identical
/// on both sides), so this belongs here, not in the conflict report.
///
/// Deliberately diffs each side against `merge_base`, NOT against each
/// other: `diff_name_status(ours, theirs)` and `diff_name_status(theirs,
/// ours)` report the exact same set of changed paths (just with swapped
/// A/D status letters for adds/deletes) since a raw two-tree diff is
/// direction-symmetric in its path set — so a first version of this
/// function that diffed the two sides directly against each other always
/// computed `ours_only == theirs_only == {}`, silently dropping the
/// "which side introduced this file" signal the report schema promises.
fn non_conflicting_paths(root: &Path, merge_base: &str, ours: &str, theirs: &str) -> Value {
    let runner = GitRunner::new(root);
    if merge_base.is_empty() {
        return json!({"ours_only_paths": [], "theirs_only_paths": []});
    }
    let ours_changes = runner.diff_name_status(merge_base, ours);
    let theirs_changes = runner.diff_name_status(merge_base, theirs);

    let ours_paths: std::collections::HashSet<String> =
        ours_changes.iter().map(|(_, p)| p.clone()).collect();
    let theirs_paths: std::collections::HashSet<String> =
        theirs_changes.iter().map(|(_, p)| p.clone()).collect();

    let ours_only: Vec<String> = ours_paths.difference(&theirs_paths).cloned().collect();
    let theirs_only: Vec<String> = theirs_paths.difference(&ours_paths).cloned().collect();

    json!({
        "ours_only_paths": ours_only,
        "theirs_only_paths": theirs_only,
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    fn init_repo_with_remote(root: &Path, remote: &Path) {
        std::process::Command::new("git")
            .arg("init")
            .arg("-q")
            .arg("-b")
            .arg("main")
            .arg(root)
            .status()
            .unwrap();
        std::process::Command::new("git")
            .arg("-C")
            .arg(root)
            .args(["config", "user.email", "t@t"])
            .status()
            .unwrap();
        std::process::Command::new("git")
            .arg("-C")
            .arg(root)
            .args(["config", "user.name", "t"])
            .status()
            .unwrap();
        pin_builtin_merge(root);
        std::fs::write(root.join("a.txt"), b"a").unwrap();
        std::process::Command::new("git")
            .arg("-C")
            .arg(root)
            .args(["add", "."])
            .status()
            .unwrap();
        std::process::Command::new("git")
            .arg("-C")
            .arg(root)
            .args(["commit", "-qm", "init"])
            .status()
            .unwrap();
        std::process::Command::new("git")
            .arg("init")
            .arg("--bare")
            .arg("-q")
            .arg(remote)
            .status()
            .unwrap();
        // Point the bare remote's HEAD at main: without init.defaultBranch
        // configured on the machine, HEAD dangles at refs/heads/master, so
        // later clones check out nothing — their commits then land on a
        // fresh `master` and never reach `main`, silently turning every
        // "diverged" fixture into "ahead".
        std::process::Command::new("git")
            .arg("-C")
            .arg(remote)
            .args(["symbolic-ref", "HEAD", "refs/heads/main"])
            .status()
            .unwrap();
        std::process::Command::new("git")
            .arg("-C")
            .arg(root)
            .args(["remote", "add", "origin", remote.to_str().unwrap()])
            .status()
            .unwrap();
        std::process::Command::new("git")
            .arg("-C")
            .arg(root)
            .args(["push", "-u", "origin", "main"])
            .status()
            .unwrap();
    }

    /// Forces git's built-in text merge on every path of the fixture repo.
    /// `reconcile` runs git through the runner, which inherits the
    /// developer's global config: a `* merge=mergiraf` line in
    /// `core.attributesFile` resolves the fixtures' conflicts cleanly, so the
    /// conflict paths under test are never reached. `.git/info/attributes`
    /// outranks both `core.attributesFile` and in-tree `.gitattributes`.
    fn pin_builtin_merge(root: &Path) {
        let info = root.join(".git").join("info");
        std::fs::create_dir_all(&info).unwrap();
        std::fs::write(info.join("attributes"), "* merge=text\n").unwrap();
    }

    #[test]
    fn reconcile_up_to_date() {
        let dir = tempdir().unwrap();
        let remote = tempdir().unwrap();
        init_repo_with_remote(dir.path(), remote.path());

        let opts = ReconcileOptions {
            strategy: "report".to_string(),
            push: "none".to_string(),
            request_id: format!("rec-{}", uuid::Uuid::new_v4()),
            into_target: None,
        };
        let result = reconcile(dir.path(), &opts).unwrap();
        assert_eq!(result["state"], json!("up_to_date"));
    }

    #[test]
    fn reconcile_fast_forward() {
        let dir = tempdir().unwrap();
        let remote = tempdir().unwrap();
        init_repo_with_remote(dir.path(), remote.path());

        // Make a new commit on the remote.
        let clone_dir = tempdir().unwrap();
        std::process::Command::new("git")
            .arg("clone")
            .arg("-q")
            .arg(remote.path())
            .arg(clone_dir.path())
            .status()
            .unwrap();
        std::process::Command::new("git")
            .arg("-C")
            .arg(clone_dir.path())
            .args(["config", "user.email", "t@t"])
            .status()
            .unwrap();
        std::process::Command::new("git")
            .arg("-C")
            .arg(clone_dir.path())
            .args(["config", "user.name", "t"])
            .status()
            .unwrap();
        std::fs::write(clone_dir.path().join("b.txt"), b"b").unwrap();
        std::process::Command::new("git")
            .arg("-C")
            .arg(clone_dir.path())
            .args(["add", "."])
            .status()
            .unwrap();
        std::process::Command::new("git")
            .arg("-C")
            .arg(clone_dir.path())
            .args(["commit", "-qm", "remote commit"])
            .status()
            .unwrap();
        std::process::Command::new("git")
            .arg("-C")
            .arg(clone_dir.path())
            .args(["push"])
            .status()
            .unwrap();

        let opts = ReconcileOptions {
            strategy: "report".to_string(),
            push: "none".to_string(),
            request_id: format!("rec-{}", uuid::Uuid::new_v4()),
            into_target: None,
        };
        let result = reconcile(dir.path(), &opts).unwrap();
        assert_eq!(result["state"], json!("fast_forwarded"));
    }

    #[test]
    fn reconcile_diverged_reports() {
        let dir = tempdir().unwrap();
        let remote = tempdir().unwrap();
        init_repo_with_remote(dir.path(), remote.path());

        // Diverge: local commit.
        std::fs::write(dir.path().join("local.txt"), b"local").unwrap();
        std::process::Command::new("git")
            .arg("-C")
            .arg(dir.path())
            .args(["add", "."])
            .status()
            .unwrap();
        std::process::Command::new("git")
            .arg("-C")
            .arg(dir.path())
            .args(["commit", "-qm", "local"])
            .status()
            .unwrap();

        // Remote commit.
        let clone_dir = tempdir().unwrap();
        std::process::Command::new("git")
            .arg("clone")
            .arg("-q")
            .arg(remote.path())
            .arg(clone_dir.path())
            .status()
            .unwrap();
        std::process::Command::new("git")
            .arg("-C")
            .arg(clone_dir.path())
            .args(["config", "user.email", "t@t"])
            .status()
            .unwrap();
        std::process::Command::new("git")
            .arg("-C")
            .arg(clone_dir.path())
            .args(["config", "user.name", "t"])
            .status()
            .unwrap();
        std::fs::write(clone_dir.path().join("remote.txt"), b"remote").unwrap();
        std::process::Command::new("git")
            .arg("-C")
            .arg(clone_dir.path())
            .args(["add", "."])
            .status()
            .unwrap();
        std::process::Command::new("git")
            .arg("-C")
            .arg(clone_dir.path())
            .args(["commit", "-qm", "remote"])
            .status()
            .unwrap();
        std::process::Command::new("git")
            .arg("-C")
            .arg(clone_dir.path())
            .args(["push"])
            .status()
            .unwrap();

        let opts = ReconcileOptions {
            strategy: "report".to_string(),
            push: "none".to_string(),
            request_id: format!("rec-{}", uuid::Uuid::new_v4()),
            into_target: None,
        };
        let result = reconcile(dir.path(), &opts).unwrap();
        assert_eq!(result["state"], json!("diverged"));
        assert!(result["ahead"].as_u64().unwrap() >= 1);
        assert!(result["behind"].as_u64().unwrap() >= 1);
    }

    #[test]
    fn reconcile_defaults_empty_request_id() {
        // Regression: pixel-daemon's op_reconcile currently dispatches with
        // request_id == "" (pixel-proto's Reconcile request carries none).
        // journal.begin rejects an empty request id outright, so this must
        // not be allowed to reach the journal unmodified.
        let dir = tempdir().unwrap();
        let remote = tempdir().unwrap();
        init_repo_with_remote(dir.path(), remote.path());

        let opts = ReconcileOptions {
            strategy: "report".to_string(),
            push: "none".to_string(),
            request_id: String::new(),
            into_target: None,
        };
        let result = reconcile(dir.path(), &opts).unwrap();
        assert_eq!(result["state"], json!("up_to_date"));
    }

    #[test]
    fn is_pixel_sidecar_classifies_correctly() {
        assert!(is_pixel_sidecar(".pixel"));
        assert!(is_pixel_sidecar(".pixel/actions.jsonl"));
        assert!(is_pixel_sidecar(".pixel/state.json"));
        // Legacy sidecar: `pixel migrate` is opt-in, so pre-migration repos
        // still carry `.gitpixel/` dirt — same class, same filtering.
        assert!(is_pixel_sidecar(".gitpixel"));
        assert!(is_pixel_sidecar(".gitpixel/old"));
        assert!(!is_pixel_sidecar("src/main.rs"));
        assert!(!is_pixel_sidecar("pixel.md"));
        assert!(!is_pixel_sidecar(".pixelrc"));
        assert!(!is_pixel_sidecar("sub/.pixel/nested"));
    }

    #[test]
    fn sidecar_filter_is_status_aware() {
        // Only UNTRACKED sidecar entries are ignorable. A tracked `.pixel/`
        // file (e.g. a committed targets.json) with modifications is real
        // dirtiness a rebase could clobber — it must count.
        assert!(ignorable_sidecar_entry("??", ".pixel/actions.jsonl"));
        assert!(ignorable_sidecar_entry("??", ".gitpixel/index"));
        assert!(!ignorable_sidecar_entry(" M", ".pixel/targets.json"));
        assert!(!ignorable_sidecar_entry("M ", ".pixel/targets.json"));
        assert!(!ignorable_sidecar_entry("A ", ".pixel/targets.json"));
        assert!(!ignorable_sidecar_entry(" D", ".pixel/targets.json"));
        assert!(!ignorable_sidecar_entry("UU", ".pixel/targets.json"));
        assert!(!ignorable_sidecar_entry("??", "src/main.rs"));
    }

    #[test]
    fn reconcile_rebase_if_clean_ignores_pixel_sidecar() {
        // Regression: pixel's own daemon writes `.pixel/` artifacts (index,
        // graph, action log) into the worktree. These are untracked, never
        // touched by rebase, and regenerated on demand — but the clean-
        // worktree gate treated them as dirty, blocking every
        // `rebase-if-clean` / `--into` call in a repo with an active daemon.
        // The gate must filter them out.
        let dir = tempdir().unwrap();
        let remote = tempdir().unwrap();
        init_repo_with_remote(dir.path(), remote.path());

        // Simulate daemon sidecar writes.
        std::fs::create_dir_all(dir.path().join(".pixel")).unwrap();
        std::fs::write(dir.path().join(".pixel/actions.jsonl"), b"{}").unwrap();
        std::fs::write(dir.path().join(".pixel/state.json"), b"{}").unwrap();

        // Add a local commit so the branch is "ahead" (diverged path).
        std::fs::write(dir.path().join("local.txt"), b"local").unwrap();
        std::process::Command::new("git")
            .arg("-C")
            .arg(dir.path())
            .args(["add", "."])
            .status()
            .unwrap();
        std::process::Command::new("git")
            .arg("-C")
            .arg(dir.path())
            .args(["commit", "-qm", "local"])
            .status()
            .unwrap();

        // Add a remote commit so the branch is "behind" (diverged).
        let clone_dir = tempdir().unwrap();
        std::process::Command::new("git")
            .arg("clone")
            .arg("-q")
            .arg(remote.path())
            .arg(clone_dir.path())
            .status()
            .unwrap();
        std::process::Command::new("git")
            .arg("-C")
            .arg(clone_dir.path())
            .args(["config", "user.email", "t@t"])
            .status()
            .unwrap();
        std::process::Command::new("git")
            .arg("-C")
            .arg(clone_dir.path())
            .args(["config", "user.name", "t"])
            .status()
            .unwrap();
        std::fs::write(clone_dir.path().join("remote.txt"), b"remote").unwrap();
        std::process::Command::new("git")
            .arg("-C")
            .arg(clone_dir.path())
            .args(["add", "."])
            .status()
            .unwrap();
        std::process::Command::new("git")
            .arg("-C")
            .arg(clone_dir.path())
            .args(["commit", "-qm", "remote"])
            .status()
            .unwrap();
        std::process::Command::new("git")
            .arg("-C")
            .arg(clone_dir.path())
            .args(["push"])
            .status()
            .unwrap();

        let opts = ReconcileOptions {
            strategy: "rebase-if-clean".to_string(),
            push: "none".to_string(),
            request_id: format!("rec-sidecar-{}", uuid::Uuid::new_v4()),
            into_target: None,
        };
        let result = reconcile(dir.path(), &opts).unwrap();
        // Must NOT be an UNSUPPORTED_STATE error about dirty files — the
        // `.pixel/` sidecar is filtered. With non-overlapping changes the
        // rebase is clean, so state should be "diverged" with
        // clean_rebase_possible=true (or "up_to_date" after the rebase).
        assert_ne!(
            result["state"],
            json!("error"),
            "rebase-if-clean must not be blocked by .pixel/ sidecar: {result}"
        );
        assert!(
            result
                .get("clean_rebase_possible")
                .is_none_or(|v| v == true),
            "sidecar dirtiness must not prevent clean rebase: {result}"
        );
    }

    #[test]
    fn reconcile_rebase_if_clean_refuses_on_tracked_sidecar_modification() {
        // The inverse guarantee of the sidecar filter: a TRACKED `.pixel/`
        // file with uncommitted modifications is genuine dirtiness — the
        // rebase would clobber it, so the gate must refuse. Only untracked
        // (`??`) sidecar entries are ignorable.
        let dir = tempdir().unwrap();
        let remote = tempdir().unwrap();
        init_repo_with_remote(dir.path(), remote.path());

        // Commit a tracked sidecar file, then modify it without committing.
        // `add -f`: a developer's global excludes file (`~/.config/git/ignore`)
        // commonly lists `.pixel/`, and git honours it whatever
        // `GIT_CONFIG_GLOBAL` says. Without `-f` the add is refused, the
        // commit never happens, the file is untracked (so filtered as
        // sidecar noise), and the reconcile fast-forwards — the test then
        // fails on its own premise, not on the gate it checks.
        std::fs::create_dir_all(dir.path().join(".pixel")).unwrap();
        std::fs::write(dir.path().join(".pixel/targets.json"), b"{\"v\":1}").unwrap();
        let added = std::process::Command::new("git")
            .arg("-C")
            .arg(dir.path())
            .args(["add", "-f", ".pixel/targets.json"])
            .status()
            .unwrap();
        assert!(
            added.success(),
            "git add -f of the sidecar file must succeed"
        );
        let committed = std::process::Command::new("git")
            .arg("-C")
            .arg(dir.path())
            .args(["commit", "-qm", "track sidecar file"])
            .status()
            .unwrap();
        assert!(committed.success(), "the sidecar file must be committed");
        let tracked = std::process::Command::new("git")
            .arg("-C")
            .arg(dir.path())
            .args(["ls-files", "--error-unmatch", ".pixel/targets.json"])
            .status()
            .unwrap();
        assert!(tracked.success(), "the sidecar file must be tracked");
        std::fs::write(dir.path().join(".pixel/targets.json"), b"{\"v\":2}").unwrap();

        // Diverge: remote gains a commit the local branch doesn't have.
        let clone_dir = tempdir().unwrap();
        std::process::Command::new("git")
            .arg("clone")
            .arg("-q")
            .arg(remote.path())
            .arg(clone_dir.path())
            .status()
            .unwrap();
        std::process::Command::new("git")
            .arg("-C")
            .arg(clone_dir.path())
            .args(["config", "user.email", "t@t"])
            .status()
            .unwrap();
        std::process::Command::new("git")
            .arg("-C")
            .arg(clone_dir.path())
            .args(["config", "user.name", "t"])
            .status()
            .unwrap();
        std::fs::write(clone_dir.path().join("remote.txt"), b"remote").unwrap();
        std::process::Command::new("git")
            .arg("-C")
            .arg(clone_dir.path())
            .args(["add", "."])
            .status()
            .unwrap();
        std::process::Command::new("git")
            .arg("-C")
            .arg(clone_dir.path())
            .args(["commit", "-qm", "remote"])
            .status()
            .unwrap();
        std::process::Command::new("git")
            .arg("-C")
            .arg(clone_dir.path())
            .args(["push"])
            .status()
            .unwrap();

        let opts = ReconcileOptions {
            strategy: "rebase-if-clean".to_string(),
            push: "none".to_string(),
            request_id: format!("rec-tracked-sidecar-{}", uuid::Uuid::new_v4()),
            into_target: None,
        };
        let err = reconcile(dir.path(), &opts)
            .expect_err("a modified TRACKED .pixel/ file must refuse rebase-if-clean");
        assert!(
            err.contains("dirty"),
            "refusal must cite dirty files, got: {err}"
        );
    }

    /// The guard reads this file to allow a raw `git rebase` after a
    /// reported conflict; a state that is never written keeps the guard
    /// closed, one that is never cleared keeps it open.
    #[test]
    fn conflict_state_is_written_with_the_count_and_cleared_afterwards() {
        let dir = tempdir().unwrap();
        let root = dir.path();
        let path = root.join(".pixel").join("reconcile-conflict.json");
        write_conflict_state(root, 3);
        let state: serde_json::Value =
            serde_json::from_str(&std::fs::read_to_string(&path).unwrap()).unwrap();
        assert_eq!(state["conflict_count"], 3);
        assert!(
            state["written_unix"].as_u64().unwrap() > 1_577_836_800,
            "{state}"
        );
        clear_conflict_state(root);
        assert!(!path.exists());
        clear_conflict_state(root); // idempotent
    }

    /// Bare repo fixture for the merge-tree and rebase helpers: `main` with
    /// `a.txt` = "base", then a `feature` branch and a diverged `main`.
    /// `conflicting` makes both sides edit the same line; otherwise they
    /// touch different files.
    fn diverged_repo(conflicting: bool) -> tempfile::TempDir {
        let dir = tempdir().unwrap();
        let root = dir.path();
        let git = |args: &[&str]| {
            let out = std::process::Command::new("git")
                .arg("-C")
                .arg(root)
                .args(args)
                .env("GIT_CONFIG_GLOBAL", "/dev/null")
                .env("GIT_AUTHOR_NAME", "t")
                .env("GIT_AUTHOR_EMAIL", "t@t")
                .env("GIT_COMMITTER_NAME", "t")
                .env("GIT_COMMITTER_EMAIL", "t@t")
                .output()
                .unwrap();
            assert!(out.status.success(), "git {args:?}: {out:?}");
        };
        git(&["init", "-q", "-b", "main"]);
        // The rebase under test commits through the runner, which sets no
        // identity: give the repo one so a `/dev/null` global config works.
        git(&["config", "user.name", "t"]);
        git(&["config", "user.email", "t@t"]);
        std::fs::write(root.join("a.txt"), "base\n").unwrap();
        git(&["add", "."]);
        git(&["commit", "-q", "-m", "base"]);
        git(&["checkout", "-q", "-b", "feature"]);
        std::fs::write(root.join("a.txt"), "feature\n").unwrap();
        git(&["commit", "-q", "-am", "feature"]);
        git(&["checkout", "-q", "main"]);
        if conflicting {
            std::fs::write(root.join("a.txt"), "main\n").unwrap();
        } else {
            std::fs::write(root.join("b.txt"), "main\n").unwrap();
            git(&["add", "."]);
        }
        git(&["commit", "-q", "-am", "main"]);
        git(&["checkout", "-q", "feature"]);
        dir
    }

    #[test]
    fn version_gate_requires_git_2_38() {
        assert!(version_supports_merge_tree_write_tree("git version 2.38.0"));
        assert!(version_supports_merge_tree_write_tree(
            "git version 2.55.0 (Apple Git-200)"
        ));
        assert!(version_supports_merge_tree_write_tree("git version 3.0.0"));
        assert!(!version_supports_merge_tree_write_tree(
            "git version 2.37.9"
        ));
        assert!(!version_supports_merge_tree_write_tree("git version 1.99"));
        assert!(!version_supports_merge_tree_write_tree("git version"));
        assert!(!version_supports_merge_tree_write_tree(""));
        assert!(!version_supports_merge_tree_write_tree("git version x.y"));
    }

    #[test]
    fn probe_merge_tree_reports_conflicts_with_their_stages_and_messages() {
        let dir = diverged_repo(true);
        let root = dir.path();
        assert!(
            git_supports_merge_tree_write_tree(root),
            "git too old for the probe"
        );
        let probe = probe_merge_tree(root, "feature", "main");
        assert!(!probe.clean, "both sides edited a.txt: {probe:?}");
        let stages = parse_stage_lines(&probe.stage_lines);
        let a = stages.get("a.txt").expect("a.txt is the conflicted path");
        assert!(
            a.contains_key(&1) && a.contains_key(&2) && a.contains_key(&3),
            "{stages:?}"
        );
        assert!(
            probe.messages.contains("CONFLICT"),
            "messages must keep git's CONFLICT lines: {:?}",
            probe.messages
        );
    }

    #[test]
    fn probe_merge_tree_is_clean_when_the_sides_touch_different_files() {
        let dir = diverged_repo(false);
        let root = dir.path();
        let probe = probe_merge_tree(root, "feature", "main");
        assert!(probe.clean, "{probe:?}");
        let tree = probe.stage_lines.lines().next().unwrap_or_default();
        assert_eq!(
            tree.len(),
            40,
            "first line is the merged tree oid: {tree:?}"
        );
        assert!(parse_stage_lines(&probe.stage_lines).is_empty());
        assert!(!probe.messages.contains("CONFLICT"));

        let missing = probe_merge_tree(root, "feature", "no-such-ref");
        assert!(!missing.clean);
        assert!(parse_stage_lines(&missing.stage_lines).is_empty());
    }

    #[test]
    fn continue_rebase_finishes_a_rebase_whose_conflict_was_staged() {
        let dir = diverged_repo(true);
        let root = dir.path();
        let runner = GitRunner::new(root);
        // No rebase in progress: nothing to continue, must report false.
        assert!(!continue_rebase(&runner));

        let started = runner.run_output(&["rebase", "main"], &[]).unwrap();
        assert!(!started.success(), "the rebase must stop on the conflict");
        assert!(rebase_in_progress(root));
        std::fs::write(root.join("a.txt"), "resolved\n").unwrap();
        runner.run(&["add", "a.txt"]).unwrap();

        assert!(continue_rebase(&runner));
        assert!(!rebase_in_progress(root));
        let head = String::from_utf8(runner.run(&["log", "-1", "--format=%s"]).unwrap()).unwrap();
        assert_eq!(head.trim(), "feature");
        let parent =
            String::from_utf8(runner.run(&["log", "-1", "--format=%s", "HEAD~1"]).unwrap())
                .unwrap();
        assert_eq!(parent.trim(), "main", "feature is replayed on top of main");
    }

    #[test]
    fn reconcile_into_auto_resolves_an_additive_conflict_and_continues_the_rebase() {
        // Both sides append a different line to `a.txt`: the rebase stops on
        // the conflict, the union merge keeps both lines, and the rebase is
        // continued through the runner. The answer must say what happened
        // (`rebased` with the resolved path) and HEAD must be the feature
        // commit replayed on top of main. (The local target is not moved on
        // this path today, unlike the clean `integrated` path; that gap is
        // tracked separately and not asserted here.)
        let dir = tempdir().unwrap();
        let remote = tempdir().unwrap();
        let root = dir.path();
        init_repo_with_remote(root, remote.path());
        assert_additive_conflict_is_auto_resolved(root);
    }

    #[test]
    fn reconcile_fixture_should_reach_the_conflict_path_when_a_user_merge_driver_is_configured() {
        // A developer's global config maps every path to a syntax-aware
        // merge driver (mergiraf) that resolves the additive conflict by
        // itself, so the probe comes back clean and the reconcile takes the
        // `integrated` path instead of the auto-resolution under test. The
        // same attribute slot is reachable from the repo config: a driver
        // that always merges cleanly, installed after the fixture, must not
        // change the outcome.
        let dir = tempdir().unwrap();
        let remote = tempdir().unwrap();
        let root = dir.path();
        init_repo_with_remote(root, remote.path());
        let user_config = tempdir().unwrap();
        let user_attributes = user_config.path().join("attributes");
        std::fs::write(&user_attributes, "* merge=always-clean\n").unwrap();
        for (key, value) in [
            ("core.attributesFile", user_attributes.to_str().unwrap()),
            (
                "merge.always-clean.driver",
                "git merge-file --union %A %O %B",
            ),
        ] {
            let status = std::process::Command::new("git")
                .arg("-C")
                .arg(root)
                .args(["config", key, value])
                .status()
                .unwrap();
            assert!(status.success(), "git config {key}");
        }
        assert_additive_conflict_is_auto_resolved(root);
    }

    /// Makes `feature` and `main` append a different line to `a.txt`, then
    /// checks that `reconcile --into main` stops on the conflict, resolves
    /// it by union and finishes the rebase.
    fn assert_additive_conflict_is_auto_resolved(root: &Path) {
        let git = |args: &[&str]| {
            let out = std::process::Command::new("git")
                .arg("-C")
                .arg(root)
                .args(args)
                .output()
                .unwrap();
            assert!(out.status.success(), "git {args:?}: {out:?}");
            String::from_utf8_lossy(&out.stdout).trim().to_string()
        };
        git(&["checkout", "-q", "-b", "feature"]);
        std::fs::write(root.join("a.txt"), "a\nfeature\n").unwrap();
        git(&["commit", "-qam", "feature line"]);
        git(&["checkout", "-q", "main"]);
        std::fs::write(root.join("a.txt"), "a\nmain\n").unwrap();
        git(&["commit", "-qam", "main line"]);
        git(&["push", "-q", "origin", "main"]);
        git(&["checkout", "-q", "feature"]);

        let opts = ReconcileOptions {
            strategy: "report".to_string(),
            push: "none".to_string(),
            request_id: format!("rec-{}", uuid::Uuid::new_v4()),
            into_target: Some("main".to_string()),
        };
        let result = reconcile(root, &opts).unwrap();
        assert_eq!(result["state"], json!("rebased"), "{result}");
        assert_eq!(result["auto_resolved"], json!(["a.txt"]), "{result}");
        assert!(!rebase_in_progress(root));
        let content = std::fs::read_to_string(root.join("a.txt")).unwrap();
        assert!(
            content.contains("main\n") && content.contains("feature\n"),
            "union merge keeps both sides: {content:?}"
        );
        assert!(!content.contains("<<<<<<<"), "{content:?}");
        let head = git(&["rev-parse", "HEAD"]);
        assert_eq!(result["to"], json!(head));
        assert_eq!(git(&["log", "-1", "--format=%s"]), "feature line");
        assert_eq!(git(&["log", "-1", "--format=%s", "HEAD~1"]), "main line");
    }
}
